import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import {fixtures} from './native-network.mjs';
async function start(page){const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).journeySetup());await page.getByRole('button',{name:'Открыть по 12 словам',exact:true}).click();await page.getByRole('button',{name:'Открыть из файла',exact:true}).click();await page.locator('input[type=file]').setInputFiles({name:'archive.json',mimeType:'application/json',buffer:Buffer.from(v.family.serialized)});await page.getByRole('textbox',{name:'12 слов восстановления SEJIRE'}).fill(v.family.words);await page.getByRole('button',{name:'Восстановить архив',exact:true}).click();await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();await page.getByRole('button',{name:'Сохранить через Solana',exact:true}).click();return {f,v};}
async function order(page){await mkdir('test-results/mvp-screens',{recursive:true});await page.screenshot({path:'test-results/mvp-screens/creation-confirmation.png',fullPage:true});await page.getByRole('button',{name:'Продолжить с Phantom',exact:true}).click();await page.getByRole('checkbox',{name:'Подтверждаю показанные суммы и сеть'}).check();await expect(page.getByRole('button',{name:/^Оплатить /})).toBeEnabled();await page.screenshot({path:'test-results/mvp-screens/payment-confirmation.png',fullPage:true});}
test('one-window editor payment operator upload retrieve hash and clean offline two-tree restore',async({page,browser})=>{
 const {f,v}=await start(page);await expect(page.getByLabel('Доверенный genesis SHA-256')).not.toBeVisible();await mkdir('test-results/mvp-screens',{recursive:true});await page.screenshot({path:'test-results/mvp-screens/user-saving.png',fullPage:true});await order(page);const expectedVault=await page.evaluate(async words=>{const job=(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1);return (await import('/src/lib/crypto/vault.ts')).openEnvelope((await import('/src/lib/crypto/keys.ts')).deriveKeysFromMnemonic(words),JSON.parse(job.ciphertext));},v.family.words);await page.getByRole('button',{name:/^Оплатить /}).click();await expect(page.getByRole('status')).toContainText('Оплата подтверждена');expect(f.network.sends).toBe(1);await page.screenshot({path:'test-results/mvp-screens/waiting-storage.png',fullPage:true});await page.getByRole('button',{name:'Открыть это сохранение в админке'}).click();await expect(page.getByRole('button',{name:'Сохранить в хранилище',exact:true})).toBeVisible();await page.screenshot({path:'test-results/mvp-screens/operator-saving.png',fullPage:true});await page.getByRole('button',{name:'Обзор',exact:true}).click();await page.screenshot({path:'test-results/mvp-screens/admin-overview.png',fullPage:true});await page.getByRole('button',{name:'Сохранения',exact:true}).click();page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Сохранить в хранилище',exact:true}).click();await expect(page.getByRole('status')).toContainText('Загрузка подписана и сохранена');expect(f.network.arPosts).toBe(0);await page.reload();await expect(page.getByRole('button',{name:'Продолжить отправку',exact:true})).toBeEnabled();const before=await page.evaluate(async()=>{const jobs=await(await import('/src/lib/native/cache.ts')).cachedJobs();return {id:jobs.at(-1).arPlan.id,ciphertext:jobs.at(-1).ciphertext};});await page.getByRole('button',{name:'Продолжить отправку',exact:true}).click();await expect(page.getByRole('status')).toContainText('Данные отправлены');expect(f.network.arPosts).toBe(1);expect(f.network.arId).toBe(before.id);expect(f.network.payload).toBe(before.ciphertext);await page.goto('/#/save?order='+await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).readCache('active-saving'))));await expect(page.getByRole('button',{name:'Открыть дерево',exact:true})).toBeVisible();await page.screenshot({path:'test-results/mvp-screens/completed.png',fullPage:true});expect(f.network.sends).toBe(1);await page.getByRole('button',{name:'Открыть дерево',exact:true}).click();await expect(page.getByText('Архив получен и проверен. Введите свои слова SEJIRE для расшифровки.',{exact:true})).toBeVisible();
 const clean=await browser.newContext();const p=await clean.newPage();await fixtures(p);await p.goto('/');await p.getByRole('button',{name:'Открыть по 12 словам',exact:true}).click();await p.getByRole('button',{name:'Открыть из файла',exact:true}).click();await p.locator('input[type=file]').setInputFiles({name:'retrieved.json',mimeType:'application/json',buffer:Buffer.from(f.network.payload)});await p.getByRole('textbox',{name:'12 слов восстановления SEJIRE'}).fill(v.family.words);await p.evaluate(async()=>{window.fixtureRecovered=(await import('/tests/browser-fixture.ts')).recovered;});await clean.setOffline(true);await p.getByRole('button',{name:'Восстановить архив',exact:true}).click();await expect(p.getByRole('button',{name:'Сохранить',exact:true}).first()).toBeVisible();const restored=await p.evaluate(async words=>window.fixtureRecovered(words),v.family.words);expect(expectedVault).not.toBeNull();expect(restored).toEqual(expectedVault);expect(restored).toMatchObject({trees:v.family.vault.trees});expect(Object.keys(restored.trees)).toHaveLength(2);await clean.close();expect(f.forbidden).toEqual([]);
});
for(const mode of ['reject','lost','pre-window-error'])test('payment '+mode+' keeps attempt and never silently creates a new charge',async({page})=>{
 const {f}=await start(page);await order(page);if(mode==='reject')await page.evaluate(()=>window.fixtureWallet.reject=true);if(mode==='lost')f.network.loseResponse=true;if(mode==='pre-window-error')await page.route('https://api.devnet.solana.com',async r=>{const p=r.request().postDataJSON();if(p.method==='getBlockHeight')return r.fulfill({status:503,json:{error:'pre-wallet'}});return r.fallback();});await page.getByRole('button',{name:/^Оплатить /}).click();if(mode==='lost'){await expect(page.getByRole('status')).toContainText('Оплата подтверждена');expect(f.network.sends).toBe(1);}else{await expect(page.getByRole('alert')).toBeVisible();expect(f.network.sends).toBe(0);const job=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1));expect(job.signingStarted??false).toBe(false);expect(job.attempt.phase).toBe(mode==='reject'?'rejected':'prepared');}await page.reload();await page.goto('/#/save?order='+await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).readCache('active-saving'))));await expect(page.getByRole('heading',{name:'Сохранить семейную историю'})).toBeVisible();expect(f.network.sends).toBe(mode==='lost'?1:0);
});
test('legacy unknown signature survives reload and empty reference cannot clear it',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).legacyUnknownFixture());await page.goto('/#/save?order='+v.job.order.id);await expect(page.getByText('В старой записи не хватает данных, чтобы безопасно установить завершение попытки.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Продолжить сохранение',exact:true}).click();await expect(page.getByRole('status')).toContainText('Это не доказывает, что списания не было');await page.reload();const old=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1));expect(old.signingStarted).toBe(true);expect(old.paymentSignature).toBeUndefined();expect(f.network.sends).toBe(0);await page.goto('/#/admin?order='+v.job.order.id);await expect(page.getByText('Результат прежнего подтверждения неизвестен. Запись сохранена, новая оплата не запускается.',{exact:true})).toBeVisible();
});
test('expired prepared message is stopped before Phantom and cannot lose its order',async({page})=>{
 const {f}=await start(page);await order(page);await page.route('https://api.devnet.solana.com',async r=>{const p=r.request().postDataJSON();if(p.method==='getBlockHeight')return r.fulfill({json:{jsonrpc:'2.0',id:p.id,result:300}});return r.fallback();});await page.getByRole('button',{name:/^Оплатить /}).click();await expect(page.getByRole('alert')).toContainText('истёк до вызова кошелька');const result=await page.evaluate(async()=>({calls:window.fixtureWallet.signCount,job:(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1)}));expect(result.calls).toBe(0);expect(result.job.attempt.phase).toBe('expired_unexecuted');expect(result.job.signingStarted??false).toBe(false);expect(f.network.sends).toBe(0);
});
test('storage failure prevents transaction signature and broadcast',async({page})=>{
 const {f}=await start(page);await order(page);await page.evaluate(()=>{IDBObjectStore.prototype.put=function(){throw new DOMException('fixture full','QuotaExceededError');};});await page.getByRole('button',{name:/^Оплатить /}).click();await expect(page.getByRole('alert')).toContainText('Не удалось сохранить журнал');expect(await page.evaluate(()=>window.fixtureWallet.signCount)).toBe(0);expect(f.network.sends).toBe(0);await page.reload();await page.goto('/#/save?order='+await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).readCache('active-saving'))));await expect(page.getByRole('button',{name:'Продолжить сохранение',exact:true})).toBeVisible();
});
test('double click shares one attempt and reload keeps the trusted root without another setup wizard',async({page})=>{
 const {f}=await start(page);await order(page);await page.getByRole('button',{name:/^Оплатить /}).dblclick({force:true});await expect(page.getByRole('status')).toContainText('Оплата подтверждена');expect(f.network.sends).toBe(1);await page.goto('/#/admin');await expect(page.getByRole('heading',{name:'Настроим SEJIRE',exact:true})).toHaveCount(0);await page.reload();await expect(page.getByRole('heading',{name:'Настроим SEJIRE',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Сохранения',exact:true}).click();await expect(page.getByRole('table').first().locator('tbody tr')).toHaveCount(1);expect(f.network.sends).toBe(1);
});

test('unknown wallet error is durable and does not permit a fresh payment',async({page})=>{
 const {f}=await start(page);await order(page);await page.evaluate(()=>{window.phantom.solana.signTransaction=async()=>{throw Error('fixture disconnected after wallet invocation');};});await page.getByRole('button',{name:/^Оплатить /}).click();await expect(page.getByRole('alert')).toBeVisible();await page.reload();await page.goto('/#/save?order='+await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).readCache('active-saving'))));await expect(page.getByText('Результат подтверждения неизвестен. Проверка оплаты не запускает новый платёж.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Продолжить сохранение',exact:true}).click();await expect(page.getByRole('status')).toContainText('Это не доказывает, что списания не было');const job=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1));expect(job.attempt.phase).toBe('signature_unknown');expect(job.signingStarted).toBe(true);expect(f.network.sends).toBe(0);
});
test('tampered cached configuration cannot replace the pinned authority on reload',async({page})=>{
 const f=await fixtures(page);await page.goto('/');await page.evaluate(async()=>{await(await import('/tests/native-fixture.ts')).journeySetup();const cache=await import('/src/lib/native/cache.ts');const record=await cache.readCache('trusted-session');record.chain.versions[0].config.wallets.service=record.chain.versions[0].config.wallets.fund;await cache.writeCache('trusted-session',record);});await page.goto('/#/admin');await page.reload();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByText('Управляющий кошелёк подтверждён',{exact:true})).toHaveCount(0);expect(f.network.sends).toBe(0);
});

test('unchanged draft blur preserves signatures while a real price edit invalidates them',async({page})=>{
 const f=await fixtures(page);await page.goto('/');await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).journeySetup());await page.goto('/#/admin');await page.getByRole('button',{name:'Подтвердить управляющий Phantom',exact:true}).click();await page.getByRole('button',{name:'Настройки',exact:true}).click();await page.getByLabel('Цена сохранения (SOL)',{exact:true}).fill('0.03');await page.getByRole('heading',{name:'Настройки проекта',exact:true}).click();await page.getByRole('button',{name:'Диагностика разработчика',exact:true}).click();await expect(page.getByText(/^Подписи: 1; принятие: 1\./)).toBeVisible();await page.getByLabel('Цена SOL',{exact:true}).fill('0.04');await page.getByRole('heading',{name:'Новая версия настроек · Черновик',exact:true}).click();await expect(page.getByText(/^Подписи: 0; принятие: 0\./)).toBeVisible();const record=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).readCache('trusted-session')));expect(record.chain.versions[0].config.serviceLamports).toBe('30000000');expect(f.network.sends).toBe(0);
});
test('owner preparation signs a reviewed successor and returns to the same encrypted saving without payment',async({page})=>{
 const {f}=await start(page);await expect(page.getByRole('button',{name:'Продолжить с Phantom',exact:true})).toBeEnabled();await expect.poll(()=>page.evaluate(async()=>(await import('/src/lib/native/cache.ts')).readCache('saving-ciphertext'))).toBeTruthy();await page.goto('/#/admin?prepare=1');page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Подготовить это сохранение',exact:true}).click();await expect(page.getByRole('heading',{name:'Сохранить семейную историю'})).toBeVisible();await expect(page.getByRole('button',{name:'Продолжить с Phantom',exact:true})).toBeEnabled();const result=await page.evaluate(async()=>{const c=await import('/src/lib/native/cache.ts');return {record:await c.readCache('trusted-session'),archive:await c.readCache('saving-ciphertext'),jobs:await c.cachedJobs()};});expect(result.record.chain.versions).toHaveLength(2);expect(result.archive).toBeTruthy();expect(result.jobs).toHaveLength(0);expect(f.network.sends).toBe(0);
});

test('mobile one-window saving keeps price next action and payment status within viewport',async({page})=>{
 await page.setViewportSize({width:390,height:844});const {f}=await start(page);await expect(page.locator('.saving-total')).toContainText('0.03 SOL');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await mkdir('test-results/mvp-screens',{recursive:true});await page.screenshot({path:'test-results/mvp-screens/mobile-saving.png',fullPage:true});await order(page);await page.getByRole('button',{name:/^Оплатить /}).click();await expect(page.getByRole('status')).toContainText('Оплата подтверждена');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(f.network.sends).toBe(1);
});

test('expired unsigned order is preserved and explicit owner consent links a successor after readiness signature',async({page})=>{
 const {f}=await start(page);await order(page);const original=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1));await page.evaluate(()=>{const now=Date.now.bind(Date);Date.now=()=>now()+31*60*1000;});await page.goto('/#/admin?order='+original.order.id);page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Подготовить это сохранение',exact:true}).click();await expect(page.getByRole('button',{name:'Продолжить сохранение',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Продолжить сохранение',exact:true}).click();await page.getByRole('checkbox',{name:'Подтверждаю показанные суммы и сеть'}).check();await expect(page.getByRole('button',{name:/^Оплатить /})).toBeEnabled();const jobs=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()));expect(jobs).toHaveLength(2);expect(jobs.find(j=>j.order.id===original.order.id).order).toEqual(original.order);const next=jobs.find(j=>j.order.id!==original.order.id);expect(next.supersedes).toBe(original.order.id);expect(next.order.policyVersion).toBe('config-2');expect(next.ciphertext).toBe(original.ciphertext);expect(f.network.sends).toBe(0);
});

test('signed bytes cannot be rebroadcast after their signed order deadline',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const result=await page.evaluate(async()=>{const v=await(await import('/tests/native-fixture.ts')).jobFixture();const now=Date.now.bind(Date);Date.now=()=>v.job.order.expiresAt+1;try{await(await import('/src/lib/native/payment.ts')).resumeSignedPayment(v.config,v.job);return 'unexpected broadcast';}catch(e){return e.message;}finally{Date.now=now;}});expect(result).toBe('signed_payment_expired_not_broadcast');expect(f.network.sends).toBe(0);
});

test('closing and reopening the saving window keeps the exact prepared ciphertext before any order exists',async({page})=>{
 const {f}=await start(page);await expect(page.getByRole('button',{name:'Продолжить с Phantom',exact:true})).toBeEnabled();const before=await page.evaluate(async()=>(await import('/src/lib/native/cache.ts')).readCache('saving-ciphertext'));await page.getByRole('button',{name:'Назад',exact:true}).click();await page.getByRole('button',{name:'Сохранить через Solana',exact:true}).click();await expect(page.getByRole('status')).toContainText('Его байты сохранены');const after=await page.evaluate(async()=>(await import('/src/lib/native/cache.ts')).readCache('saving-ciphertext'));expect(after).toBe(before);expect(f.network.sends).toBe(0);
});

test('finalized failure keeps the original signature and needs explicit consent before a linked new order',async({page})=>{
 const {f}=await start(page);await order(page);await page.route('https://api.devnet.solana.com',async r=>{const p=r.request().postDataJSON();if(p.method==='getSignatureStatuses')return r.fulfill({json:{jsonrpc:'2.0',id:p.id,result:{context:{slot:100},value:f.network.tx?[{slot:100,err:{InstructionError:[0,'Custom']},confirmations:null,confirmationStatus:'finalized'}]:[null]}}});return r.fallback();});await page.getByRole('button',{name:/^Оплатить /}).click();await expect(page.getByRole('alert')).toContainText('неуспешную транзакцию');const old=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1));expect(old.attempt.phase).toBe('failed');expect(f.network.sends).toBe(1);page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Продолжить сохранение',exact:true}).click();await page.getByRole('checkbox',{name:'Подтверждаю показанные суммы и сеть'}).check();await expect(page.getByRole('button',{name:/^Оплатить /})).toBeEnabled();const jobs=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()));expect(jobs).toHaveLength(2);expect(jobs.find(j=>j.order.id===old.order.id).paymentSignature).toBe(old.paymentSignature);expect(jobs.find(j=>j.order.id!==old.order.id).supersedes).toBe(old.order.id);expect(f.network.sends).toBe(1);
});

test('contradicting failed RPC reply cannot overwrite an earlier finalized credit or propose a new payment',async({page})=>{
 const {f}=await start(page);await order(page);await page.getByRole('button',{name:/^Оплатить /}).click();await expect(page.getByRole('status')).toContainText('Оплата подтверждена');await page.route('https://api.devnet.solana.com',async r=>{const p=r.request().postDataJSON();if(p.method==='getSignatureStatuses')return r.fulfill({json:{jsonrpc:'2.0',id:p.id,result:{context:{slot:100},value:[{slot:100,err:{InstructionError:[0,'Custom']},confirmations:null,confirmationStatus:'finalized'}]}}});return r.fallback();});let dialogs=0;page.on('dialog',d=>{dialogs++;return d.dismiss();});await page.getByRole('button',{name:'Продолжить сохранение',exact:true}).click();await expect(page.getByRole('alert')).toContainText('противоречит ранее подтверждённой оплате');const jobs=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()));expect(jobs).toHaveLength(1);expect(jobs[0].attempt.phase).toBe('finalized');expect(dialogs).toBe(0);expect(f.network.sends).toBe(1);
});

test('unknown devnet attempt needs separate risk consent; keeps exact archive and never silently pays',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).legacyUnknownFixture());await page.goto('/#/save?order='+v.job.order.id);
 let warning='';page.once('dialog',async d=>{warning=d.message();await d.dismiss();});await page.getByRole('button',{name:'Начать новый тест',exact:true}).click();await expect.poll(()=>warning).toContain('Результат прежней попытки неизвестен');expect(warning).toContain('0,03 тестового SOL');expect((await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs())))).toHaveLength(1);
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Начать новый тест',exact:true}).click();await expect(page.getByRole('status')).toContainText('Теперь подтвердите оплату');const jobs=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()));expect(jobs).toHaveLength(2);const old=jobs.find(j=>j.order.id===v.job.order.id),next=jobs.find(j=>j.supersedes===v.job.order.id);expect(old).toEqual(v.job);expect(next.ciphertext).toBe(v.job.ciphertext);expect(next.order.reference).not.toBe(v.job.order.reference);expect(next.paymentSignature).toBeUndefined();expect(f.network.sends).toBe(0);await expect(page.getByRole('button',{name:/^Оплатить /})).toBeDisabled();await page.reload();expect(f.network.sends).toBe(0);
});
test('risk exit has no mainnet equivalent and archived digest can have only one signed upload',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const allowed=await page.evaluate(async()=>{const {canStartDevnetRiskTest}=await import('/src/lib/native/presentation.ts');const v=await(await import('/tests/native-fixture.ts')).legacyUnknownFixture();return {devnet:canStartDevnetRiskTest(v.job),mainnet:canStartDevnetRiskTest({...v.job,order:{...v.job.order,network:'mainnet-beta'}})};});expect(allowed).toEqual({devnet:true,mainnet:false});expect(f.network.sends).toBe(0);
});
test('ordinary saving hides technical fields, has one primary action, and separates real AR from test SOL',async({page})=>{
 const {f}=await start(page);const panel=page.getByRole('region',{name:'Сохранение семейной истории'});await expect(panel.locator('.saving-primary')).toHaveCount(1);await expect(panel.getByRole('button',{name:'Продолжить с Phantom',exact:true})).toBeEnabled();await expect(panel.getByText(/Оплата SOL — тестовая сеть/)).toBeVisible();await expect(panel.getByText(/Хранение AR — основная сеть, реальные средства/)).toBeVisible();for(const label of ['Доверенный genesis SHA-256','Подписанная конфигурация'])await expect(page.getByLabel(label)).not.toBeVisible();await expect(page.getByRole('button',{name:'Подготовить неподписанный платёж'})).toHaveCount(0);expect(f.network.sends).toBe(0);
});

test('wallet deadline preserves unknown attempt; late signed bytes never broadcast automatically',async({page})=>{
 const {f}=await start(page);await order(page);await page.evaluate(()=>{const original=window.phantom.solana.signTransaction;window.phantom.solana.signTransaction=tx=>new Promise((resolve,reject)=>{window.finishLateSignature=()=>original(tx).then(resolve,reject);});});await page.clock.install();await page.getByRole('button',{name:/^Оплатить /}).click();await expect.poll(()=>page.evaluate(()=>typeof window.finishLateSignature)).toBe('function');await page.clock.fastForward(60001);await expect(page.getByRole('alert')).toContainText('Кошелёк не ответил за минуту');expect(f.network.sends).toBe(0);let job=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1));expect(job.attempt.phase).toBe('signature_unknown');expect(job.signingStarted).toBe(true);await page.evaluate(()=>window.finishLateSignature());await expect.poll(()=>page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1).paymentSignature)).toBeTruthy();job=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1));expect(job.signedPayment).toBeTruthy();expect(job.attempt.phase).toBe('signed');expect(f.network.sends).toBe(0);
});
test('two related payments do not authorize a second upload of the same encrypted snapshot',async({page})=>{
 const {f}=await start(page);await order(page);await page.getByRole('button',{name:/^Оплатить /}).click();await expect(page.getByRole('status')).toContainText('Оплата подтверждена');await page.evaluate(async()=>{const c=await import('/src/lib/native/cache.ts'),s=(await import('/src/lib/native/session.ts')).nativeSession(),old=(await c.cachedJobs()).at(-1),w=(await import('/src/lib/native/payment.ts')).solWallet();const next=await(await import('/src/lib/native/jobs.ts')).newJob(s.config,old.order.payer,'0',JSON.parse(old.ciphertext),w,old.order.id);next.arSigningStarted=true;await c.saveJob(next);});await page.getByRole('button',{name:'Открыть это сохранение в админке'}).click();await expect(page.getByRole('button',{name:'Сохранить в хранилище',exact:true})).toBeVisible();await page.getByRole('button',{name:'Сохранить в хранилище',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Этот архив уже передан на сохранение');expect(f.network.arPosts).toBe(0);expect(f.network.sends).toBe(1);
});

test('new user creates a tree protects one SEJIRE key and reaches operator without technical forms',async({page})=>{
 const f=await fixtures(page);await page.goto('/');await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).journeySetup());await page.getByRole('button',{name:'Создать моё древо',exact:true}).click();await page.getByRole('button',{name:'Добавить себя',exact:true}).click();await page.locator('.add-modal input').fill('Тестовая семья');await page.locator('.add-modal button[type=submit]').click();await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();await page.getByRole('button',{name:'Создать 12 слов',exact:true}).click();const words=(await page.locator('.seed-grid li').allTextContents()).map(v=>v.replace(/^\s*\d+\.\s*/, '').trim()).join(' ');await page.getByRole('button',{name:'Я записал(а)',exact:true}).click();await page.locator('.modal textarea[required]').fill(words);await page.getByRole('button',{name:'Далее',exact:true}).click();await page.getByRole('button',{name:'Сохранить через Solana',exact:true}).click();await expect(page.getByRole('heading',{name:'Сохранить семейную историю',exact:true})).toBeVisible();await expect(page.getByText('Ключ подготовлен в этом сеансе. Храните слова отдельно.',{exact:true})).toBeVisible();await order(page);await page.getByRole('button',{name:/^Оплатить /}).click();await expect(page.getByRole('region',{name:'Сохранение семейной истории'}).getByRole('status')).toContainText('Ваше дерево ожидает сохранения');await page.getByRole('button',{name:'Открыть это сохранение в админке',exact:true}).click();await expect(page.getByRole('button',{name:'Сохранить в хранилище',exact:true})).toBeVisible();expect(f.network.sends).toBe(1);expect(f.network.arPosts).toBe(0);expect(f.forbidden).toEqual([]);
});

test('ordinary new save ignores cached unknown order; explicit URL and operator recovery survive reload',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>{const v=await(await import('/tests/native-fixture.ts')).legacyUnknownFixture();await(await import('/src/lib/native/cache.ts')).writeCache('saving-ciphertext',JSON.stringify(v.family.envelope));return v;});
 await page.goto('/#/save');for(let i=0;i<2;i++){await expect(page.getByRole('button',{name:'Продолжить с Phantom',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Начать новый тест',exact:true})).toHaveCount(0);await expect(page.getByText('Результат прежнего подтверждения неизвестен',{exact:true})).toHaveCount(0);await expect(page.locator('.saving-total')).toContainText('0.03 SOL');if(!i)await page.reload();}
 await page.goto('/#/save?order='+v.job.order.id);for(let i=0;i<2;i++){await expect(page.getByRole('button',{name:'Начать новый тест',exact:true})).toBeVisible();await expect(page.getByText('Результат прежнего подтверждения неизвестен',{exact:true})).toBeVisible();if(!i)await page.reload();}
 await page.goto('/#/save');await expect(page.getByRole('button',{name:'Продолжить с Phantom',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Начать новый тест',exact:true})).toHaveCount(0);await page.reload();await expect(page.getByRole('button',{name:'Продолжить с Phantom',exact:true})).toBeEnabled();
 await page.goto('/#/admin?order='+v.job.order.id);await expect(page.getByRole('button',{name:'Разобрать прежнюю попытку',exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Разобрать прежнюю попытку',exact:true}).click();await expect(page).toHaveURL(new RegExp('order='+v.job.order.id));await expect(page.getByRole('button',{name:'Начать новый тест',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Начать новый тест',exact:true})).toBeVisible();expect(f.network.sends).toBe(0);expect(await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).length)).toBe(1);
});
test('new save of the same tree does not select its unknown attempt; continuing is an explicit choice',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).legacyUnknownFixture());await page.getByRole('button',{name:'Открыть по 12 словам',exact:true}).click();await page.getByRole('button',{name:'Открыть из файла',exact:true}).click();await page.locator('input[type=file]').setInputFiles({name:'archive.json',mimeType:'application/json',buffer:Buffer.from(v.family.serialized)});await page.getByRole('textbox',{name:'12 слов восстановления SEJIRE'}).fill(v.family.words);await page.getByRole('button',{name:'Восстановить архив',exact:true}).click();await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();await page.getByRole('button',{name:'Сохранить через Solana',exact:true}).click();await expect(page.getByText('Synthetic family A',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Продолжить с Phantom',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Начать новый тест',exact:true})).toHaveCount(0);await page.goto('/#/admin?order='+v.job.order.id);await page.getByRole('button',{name:'Разобрать прежнюю попытку',exact:true}).click();await expect(page.getByRole('button',{name:'Начать новый тест',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Начать новый тест',exact:true})).toBeVisible();expect(f.network.sends).toBe(0);
});

for(const failure of ['message_unsupported','message_rejected','message_invalid','payment_prepare','successor_persist'])test('successor recovery stages '+failure+' never sign payment before explicit approval',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).legacyUnknownFixture());await page.goto('/#/save?order='+v.job.order.id);
 await page.evaluate(failure=>{window.creationSignatures=0;const w=window.phantom.solana,old=w.signMessage;window.originalMessage=old;w.signMessage=async(...args)=>{window.creationSignatures++;if(failure==='message_rejected')throw Object.assign(Error('rejected'),{code:4001});if(failure==='message_invalid')return {signature:new Uint8Array(2),publicKey:w.publicKey};return old(...args);};if(failure==='message_unsupported')delete w.signMessage;if(failure==='successor_persist'){const put=IDBObjectStore.prototype.put;window.originalPut=put;IDBObjectStore.prototype.put=function(value,key){if(key==='jobs')throw Error('test_storage_full');return put.call(this,value,key);};}},failure);
 if(failure==='payment_prepare')await page.route('https://api.devnet.solana.com',async r=>{if(r.request().postDataJSON().method==='getLatestBlockhash')return r.fulfill({status:503,json:{error:'fixture unavailable'}});return r.fallback();});
 page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Начать новый тест',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();expect(await page.evaluate(()=>window.fixtureWallet.signCount)).toBe(0);expect(f.network.sends).toBe(0);
 const result=await page.evaluate(async()=>{const c=await import('/src/lib/native/cache.ts');return {jobs:await c.cachedJobs(),diagnostics:await c.readCache('saving-diagnostics')};});expect(result.diagnostics.at(-1).stage).toBe(failure==='payment_prepare'?'payment_prepare':failure==='successor_persist'?'successor_persist':'order_signature');expect(JSON.stringify(result.diagnostics)).not.toContain(v.job.ciphertext);expect(result.jobs.find(j=>j.order.id===v.job.order.id)).toEqual(v.job);
 if(failure==='payment_prepare'){
  expect(result.jobs).toHaveLength(2);const next=result.jobs.find(j=>j.supersedes===v.job.order.id);await expect(page).toHaveURL(new RegExp('order='+next.order.id));
  let reloadSignatures=0;await page.exposeFunction('recordReloadPaymentSignature',()=>{reloadSignatures++;});
  await page.addInitScript(payer=>{window.phantom={solana:{publicKey:{toString:()=>payer},async signTransaction(){await window.recordReloadPaymentSignature();throw Error('unexpected automatic payment signature');}}};},v.job.order.payer);
  await page.reload();await expect(page.getByRole('button',{name:'Продолжить сохранение',exact:true})).toBeVisible();expect(reloadSignatures).toBe(0);expect(f.network.sends).toBe(0);
 }
 else if(failure==='successor_persist'){expect(result.jobs).toHaveLength(1);await page.evaluate(()=>{IDBObjectStore.prototype.put=window.originalPut;});await page.getByRole('button',{name:'Начать новый тест',exact:true}).click();await expect(page.getByRole('heading',{name:'Теперь подтвердите оплату',exact:true})).toBeVisible();expect(await page.evaluate(()=>window.creationSignatures)).toBe(1);expect(await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).length)).toBe(2);}
 else expect(result.jobs).toHaveLength(1);
});

for(const failure of ['readiness_expired','wrong_network','wallet_connect_rejected','wrong_payer','insufficient_balance','lookup_unavailable'])test('unknown continuation boundary '+failure+' preserves old terms and never auto pays',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async mode=>{const m=await import('/tests/native-fixture.ts');return mode==='readiness_expired'?m.expiredSuccessorFixture():m.legacyUnknownFixture();},failure);await page.goto('/#/save?order='+v.job.order.id);
 await page.evaluate(mode=>{window.creationSignatures=0;const w=window.phantom.solana,old=w.signMessage;w.signMessage=(...args)=>{window.creationSignatures++;return old(...args);};if(mode==='wallet_connect_rejected')w.connect=async()=>{throw Object.assign(Error('rejected'),{code:4001});};if(mode==='wrong_payer')w.connect=async()=>{w.publicKey={toString:()=> 'ETWcxNPF3Qcwvo4NHYw6JhMiKnGwrvH1U9YEAQ3rZSWd'};};},failure);
 if(['wrong_network','insufficient_balance','lookup_unavailable'].includes(failure))await page.route('https://api.devnet.solana.com',async r=>{const p=r.request().postDataJSON();if(failure==='lookup_unavailable'&&p.method==='getSignaturesForAddress')return r.abort();if(failure==='wrong_network'&&p.method==='getGenesisHash')return r.fulfill({json:{jsonrpc:'2.0',id:p.id,result:'5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d'}});if(failure==='insufficient_balance'&&p.method==='getBalance')return r.fulfill({json:{jsonrpc:'2.0',id:p.id,result:{context:{slot:100},value:0}}});return r.fallback();});
 page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Начать новый тест',exact:true}).click();if(failure==='lookup_unavailable')await expect(page.getByRole('heading',{name:'Теперь подтвердите оплату',exact:true})).toBeVisible();else await expect(page.getByRole('alert')).toBeVisible();const jobs=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()));expect(jobs.find(j=>j.order.id===v.job.order.id)).toEqual(v.job);expect(jobs.length).toBe(['insufficient_balance','lookup_unavailable'].includes(failure)?2:1);expect(await page.evaluate(()=>window.fixtureWallet.signCount)).toBe(0);expect(f.network.sends).toBe(0);if(!['insufficient_balance','lookup_unavailable'].includes(failure))expect(await page.evaluate(()=>window.creationSignatures)).toBe(0);await page.reload();expect(f.network.sends).toBe(0);expect(await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).length)).toBe(jobs.length);
});

test('discovered finalized old payment resumes old saving without consent dialog or successor',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>{const v=await(await import('/tests/native-fixture.ts')).jobFixture();const unknown=structuredClone(v.job);delete unknown.paymentSignature;delete unknown.signedPayment;delete unknown.attempt;await(await import('/src/lib/native/session.ts')).trustChain(v.chain,v.anchor);await(await import('/src/lib/native/cache.ts')).saveJob(unknown);return {...v,unknown};});f.network.tx=v.tx;await page.route('https://api.devnet.solana.com',async r=>{const p=r.request().postDataJSON();if(p.method==='getSignaturesForAddress')return r.fulfill({json:{jsonrpc:'2.0',id:p.id,result:[{signature:v.job.paymentSignature,err:null}]}});return r.fallback();});await page.goto('/#/save?order='+v.job.order.id);let dialogs=0;page.on('dialog',d=>{dialogs++;return d.dismiss();});await page.getByRole('button',{name:'Начать новый тест',exact:true}).click();await expect(page.getByRole('status')).toContainText('Оплата подтверждена');const jobs=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()));expect(jobs).toHaveLength(1);expect(jobs[0].order).toEqual(v.unknown.order);expect(jobs[0].reconciledSignature).toBe(v.job.paymentSignature);expect(dialogs).toBe(0);expect(f.network.sends).toBe(0);expect(await page.evaluate(()=>window.fixtureWallet.signCount)).toBe(0);
});

test('two real browser tabs cannot roll trusted v4 back to stale v3',async({page,context})=>{
 await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>{const m=await import('/tests/native-fixture.ts'),v=await m.setup(),three=await m.chainThrough(v,3),four=await m.chainThrough(v,4);await(await import('/src/lib/native/session.ts')).trustChain(three,v.anchor);return {...v,three,four};});
 const tabB=await context.newPage();await fixtures(tabB);await tabB.goto('/');await tabB.evaluate(async v=>(await import('/src/lib/native/session.ts')).trustChain(v.four,v.anchor),v);
 const adopted=await page.evaluate(async v=>{const s=await(await import('/src/lib/native/session.ts')).trustChain(v.three,v.anchor),cached=await(await import('/src/lib/native/cache.ts')).readCache('trusted-session');return {memory:s.config.version,persistent:cached.chain.versions.at(-1).config.version,trusted:s.trusted};},v);
 expect(adopted).toEqual({memory:4,persistent:4,trusted:v.anchor});await page.reload();expect(await page.evaluate(async()=>(await(await import('/src/lib/native/session.ts')).restoreNativeSession()).config.version)).toBe(4);await tabB.close();
});
for(const mode of ['historical','cached'])test('existing successor restores exact '+mode+' configuration and one continuation action after reload',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async mode=>(await import('/tests/native-fixture.ts')).linkedFixture(mode),mode);await page.goto('/#/save?order='+v.job.order.id);await expect(page.locator('.saving-primary')).toHaveCount(1);await expect(page.getByRole('button',{name:'Продолжить',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Продолжить новый тест',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Продолжить',exact:true}).click();await expect(page).toHaveURL(new RegExp('order='+v.linked.order.id));await page.reload();await expect(page.getByRole('button',{name:'Продолжить сохранение',exact:true})).toBeVisible();const state=await page.evaluate(async()=>{const cache=await import('/src/lib/native/cache.ts');return {jobs:await cache.cachedJobs(),chain:(await cache.readCache('trusted-session')).chain};});expect(state.jobs).toHaveLength(2);expect(state.jobs.find(j=>j.order.id===v.linked.order.id)).toEqual(v.linked);expect(state.chain.versions).toEqual(v.extended.versions);expect(f.network.sends).toBe(0);
});
for(const mode of ['orphan','signing'])test('missing exact configuration '+mode+' preserves history and attributes diagnostic to linked order',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async mode=>(await import('/tests/native-fixture.ts')).linkedFixture(mode),mode);await page.goto('/#/save?order='+v.job.order.id);await expect(page.getByRole('button',{name:'Продолжить',exact:true})).toBeVisible();let consent='';page.on('dialog',d=>{consent=d.message();return mode==='orphan'?d.accept():d.dismiss();});await page.getByRole('button',{name:'Продолжить',exact:true}).click();
 if(mode==='orphan')await expect(page.getByRole('heading',{name:'Теперь подтвердите оплату',exact:true})).toBeVisible();else await expect(page.getByRole('alert')).toBeVisible();
 const result=await page.evaluate(async()=>{const c=await import('/src/lib/native/cache.ts');return {jobs:await c.cachedJobs(),diagnostics:await c.readCache('saving-diagnostics')};});expect(result.jobs.find(j=>j.order.id===v.job.order.id)).toEqual(v.job);expect(result.jobs.find(j=>j.order.id===v.linked.order.id)).toEqual(v.linked);
 const missing=result.diagnostics.find(d=>d.code==='unknown_order_configuration');expect(missing.stage).toBe('successor_restore');expect(missing.orderId).toBe(v.linked.order.id);expect(missing.context.binding.configHash).toBe(v.linked.configHash);expect(missing.context.binding.versions.some(x=>x.hash===v.linked.configHash)).toBe(false);expect(JSON.stringify(missing)).not.toContain(v.linked.ciphertext);
 if(mode==='orphan'){expect(consent).toContain('оплата не начиналась');expect(result.jobs).toHaveLength(3);const replacement=result.jobs.find(j=>j.supersedes===v.linked.order.id);expect(replacement.ciphertext).toBe(v.linked.ciphertext);expect(replacement.paymentSignature).toBeUndefined();await page.goto('/#/save?order='+v.job.order.id);await page.getByRole('button',{name:'Продолжить',exact:true}).click();await expect(page).toHaveURL(new RegExp('order='+replacement.order.id));expect(await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).length)).toBe(3);}
 else{expect(result.jobs).toHaveLength(2);expect(consent).toBe('');}
 expect(f.network.sends).toBe(0);
});


test('orphan replacement requires explicit consent and cancellation preserves both jobs',async({page})=>{
 const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).linkedFixture('orphan'));await page.goto('/#/save?order='+v.job.order.id);let warning='';page.on('dialog',d=>{warning=d.message();return d.dismiss();});await page.getByRole('button',{name:'Продолжить',exact:true}).click();await expect.poll(()=>warning).toContain('Подготовить новое тестовое сохранение');await expect(page.getByRole('button',{name:'Продолжить',exact:true})).toBeEnabled();const jobs=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()));expect(jobs).toHaveLength(2);expect(jobs.find(j=>j.order.id===v.linked.order.id)).toEqual(v.linked);expect(f.network.sends).toBe(0);expect(await page.evaluate(()=>window.fixtureWallet.signCount)).toBe(0);await page.reload();await expect(page.getByRole('button',{name:'Продолжить',exact:true})).toBeVisible();
});
