import { test, expect } from '@playwright/test';
import bs58 from 'bs58';
const genesis='EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG';
async function fixtures(page) {
 const forbidden=[],network={tx:null,sends:0,loseResponse:false};
 await page.route('**/*',async route=>{
 const url=route.request().url();
 if(/ardrive|turbo|workers\.dev|\/api\/checkout\//.test(url)){forbidden.push(url);await route.abort();return;}
 if(url.endsWith('/graphql'))return route.fulfill({json:{data:{transactions:{edges:[]}}}});
 if(url.startsWith('https://arweave.net/')){
 const path=new URL(url).pathname;
 if(path==='/info')return route.fulfill({json:{network:'arweave.N.1',height:100,version:5}});
 if(path.startsWith('/price/'))return route.fulfill({contentType:'text/plain',body:'1000'});
 if(path.endsWith('/balance'))return route.fulfill({contentType:'text/plain',body:'100000'});
 throw Error('unexpected AR fixture '+path);
 }
 if(url.startsWith('https://api.devnet.solana.com')) {
 const p=route.request().postDataJSON();let result;
 if(p.method==='getBlockHeight')result=100;
 else if(p.method==='getGenesisHash')result=genesis;
 else if(p.method==='getLatestBlockhash')result={context:{slot:100},value:{blockhash:'11111111111111111111111111111111',lastValidBlockHeight:200}};
 else if(p.method==='getFeeForMessage')result={context:{slot:100},value:5000};
 else if(p.method==='getBalance')result={context:{slot:100},value:1000000000};
 else if(p.method==='getSignaturesForAddress')result=[];
 else if(p.method==='getSignatureStatuses')result={context:{slot:100},value:network.tx?[{slot:100,err:null,confirmations:null,confirmationStatus:'finalized'}]:[null]};
 else if(p.method==='getTransaction')result=network.tx;
 else if(p.method==='sendTransaction'){network.sends++;network.tx=await page.evaluate(async raw=>(await import('/tests/native-fixture.ts')).decodeBroadcast(raw),p.params[0]);if(network.loseResponse){network.loseResponse=false;await route.abort('failed');return;}result=network.tx.transaction.signatures[0];}
 else throw Error('unexpected RPC fixture '+p.method);
 return route.fulfill({json:{jsonrpc:'2.0',id:p.id,result}});
 }
 if(new URL(url).hostname!=='127.0.0.1'&&new URL(url).hostname!=='localhost'){forbidden.push(url);await route.abort();return;}
 await route.continue();
 });
 await page.addInitScript(()=>localStorage.setItem('sejire.locale','ru'));
 return {forbidden,network};
}
async function setup(page){await page.goto('/#/admin');return page.evaluate(async()=> (await import('/tests/native-fixture.ts')).setup());}
async function advanced(page){await page.getByRole('button',{name:'Настройки',exact:true}).click();const d=page.locator('details.admin-advanced');if(!await d.count())await page.getByRole('button',{name:'Диагностика разработчика',exact:true}).click();if(!await d.evaluate(e=>e.open))await d.locator('summary').first().click();}
async function importConfig(page,v){const anchor={schema:'sejire/trust-anchor/v1',project:'SEJIRE',network:v.config.environment,genesisHash:v.anchor,createdAt:v.config.createdAt};await page.getByLabel('Файл доверия',{exact:true}).setInputFiles({name:'anchor.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(anchor))});await page.getByLabel('Подписанные настройки',{exact:true}).setInputFiles({name:'config.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(v.chain))});await expect(page.getByRole('status')).toContainText('Подписи и цепочка проверены');}
async function importJob(page,v){await advanced(page);await page.getByLabel('Доверенный genesis SHA-256',{exact:true}).fill(v.anchor);await page.getByLabel('Импорт конфигурации или задания').setInputFiles({name:'job.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(v.package))});await expect(page.getByRole('status')).toContainText('Задание проверено');}
async function checkoutConfig(page,v){await expect(page.getByLabel('Доверенный genesis SHA-256',{exact:true})).toHaveCount(0);}
async function openPreservation(page,family){await page.getByRole('button',{name:'Открыть по 12 словам',exact:true}).click();await page.getByRole('button',{name:'Открыть из файла',exact:true}).click();await page.locator('input[type=file]').setInputFiles({name:'archive.json',mimeType:'application/json',buffer:Buffer.from(family.serialized)});await page.getByRole('textbox',{name:'12 слов восстановления SEJIRE'}).fill(family.words);await page.getByRole('button',{name:'Восстановить архив',exact:true}).click();await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();await page.getByRole('button',{name:'Сохранить через Solana',exact:true}).click();}
const pay=async page=>{await page.getByRole('checkbox',{name:'Подтверждаю показанные суммы и сеть'}).check();await page.getByRole('button',{name:/^Оплатить /}).click();};
test('signed three-role configuration and public balances; spending disabled',async({page})=>{const f=await fixtures(page),v=await setup(page);await importConfig(page,v);await page.getByRole('button',{name:'Проверить состояние системы',exact:true}).click();await expect(page.getByRole('region',{name:'Баланс основной казны',exact:true})).toContainText('1 SOL');await page.getByRole('button',{name:'Финансы',exact:true}).click();for(const title of ['Основная казна','Фонд памяти поколений','Резерв хранения'])await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await advanced(page);for(const field of ['Основная казна SEJIRE','Фонд памяти поколений SEJIRE','AR-резерв основной казны SEJIRE'])await expect(page.getByLabel(field,{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Опубликовать конфигурацию в Arweave (сейчас отключено)'})).toBeDisabled();expect(f.forbidden).toEqual([]);});
test('tampered configuration rejected and cannot become active',async({page})=>{await fixtures(page);const v=await setup(page);v.chain.versions[0].config.serviceLamports='1';await importConfig(page,{...v,chain:{...v.chain,versions:v.chain.versions}}).catch(async()=>{await expect(page.getByRole('alert')).toContainText('Корень доверия не совпадает');});expect(await page.evaluate(async()=>(await import('/src/lib/native/cache.ts')).readCache('trusted-session'))).toBeUndefined();});
test('configuration recovery in clean browser verifies signatures and survives reload',async({page,browser})=>{await fixtures(page);const v=await setup(page);await importConfig(page,v);const ctx=await browser.newContext(),clean=await ctx.newPage();await fixtures(clean);await clean.goto('/#/admin');await importConfig(clean,v);await clean.reload();await expect(clean.getByRole('heading',{name:'Настроим SEJIRE',exact:true})).toHaveCount(0);await expect(clean.getByRole('heading',{name:'Что требует вашего внимания',exact:true})).toBeVisible();await ctx.close();});
for(const mode of ['plain','fund','donation'])test('portable '+mode+' order: finality reload immutable recipients no false archive success',async({page})=>{const f=await fixtures(page);await page.goto('/#/admin');const v=await page.evaluate(async m=>(await import('/tests/native-fixture.ts')).jobFixture(m==='fund',m==='donation'),mode);f.network.tx=v.tx;await importJob(page,v);await expect(page.getByText('Оплата проверена',{exact:true})).toBeVisible();await expect(page.getByText('Сохранение ещё не подтверждено. Архив и ход операции остаются на устройстве.',{exact:true})).toBeVisible();await page.reload();await expect(page.getByText('Оплата проверена',{exact:true})).toBeVisible();const original=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1));expect(original.order).toEqual(v.job.order);expect(original.paymentSignature).toBe(v.job.paymentSignature);expect(f.network.sends).toBe(0);expect(f.forbidden).toEqual([]);});
for(const mode of ['plain','fund','donation'])test('native user UI '+mode+' payment automatically reaches same-device operator',async({page})=>{const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).setup());await page.evaluate(async v=>(await import('/src/lib/native/session.ts')).trustChain(v.chain,v.anchor),v);if(mode==='donation')await page.getByRole('button',{name:'Поддержать сохранение других семей'}).click();else await openPreservation(page,v.family);await checkoutConfig(page,v);await page.getByLabel('Добровольный вклад SOL').fill(mode==='plain'?'0':'0.005');await page.getByRole('button',{name:'Продолжить с Phantom',exact:true}).click();await expect(page.getByRole('status')).toContainText('Заказ уже подтверждён без списания');await pay(page);await expect(page.getByRole('status')).toContainText('Оплата подтверждена');expect(f.network.sends).toBe(1);const job=await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).cachedJobs()).at(-1));expect(job.order.servicePayment.amount).toBe(mode==='donation'?'0':'30000000');expect(job.order.fundContribution.amount).toBe(mode==='plain'?'0':'5000000');await page.goto('/#/admin?order='+job.order.id);await expect(page.getByText('Оплата проверена',{exact:true})).toBeVisible();if(mode!=='plain'){await page.getByRole('button',{name:'Финансы',exact:true}).click();await page.getByRole('button',{name:'Фонд и история взносов',exact:true}).click();await expect(page.getByRole('article').filter({has:page.getByRole('heading',{name:'Всего подтверждённых взносов',exact:true})})).toContainText('0.005 SOL');}expect(f.forbidden).toEqual([]);});
test('wallet rejection retry lost reply reload never creates second payment',async({page})=>{const f=await fixtures(page);await page.goto('/');const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).setup());await page.evaluate(async v=>(await import('/src/lib/native/session.ts')).trustChain(v.chain,v.anchor),v);await page.getByRole('button',{name:'Поддержать сохранение других семей'}).click();await checkoutConfig(page,v);await page.getByLabel('Добровольный вклад SOL').fill('0.005');await page.getByRole('button',{name:'Продолжить с Phantom',exact:true}).click();await page.evaluate(()=>window.fixtureWallet.reject=true);await pay(page);await expect(page.getByRole('alert')).toContainText('Подпись явно отклонена');expect(f.network.sends).toBe(0);await page.evaluate(()=>window.fixtureWallet.reject=false);f.network.loseResponse=true;await pay(page);await expect(page.getByRole('status')).toContainText('Оплата подтверждена');await page.goto('/#/save?order='+await page.evaluate(async()=>(await(await import('/src/lib/native/cache.ts')).readCache('active-saving'))));await expect(page.getByRole('status')).toContainText('Оплата подтверждена');expect(f.network.sends).toBe(1);});
test('new installation guided setup signs both messages and exports public trust file',async({page,browser})=>{const f=await fixtures(page);await page.goto('/#/admin');await expect(page.getByRole('heading',{name:'Настроим SEJIRE',exact:true})).toBeVisible();await expect(page.getByLabel('JSON конфигурации')).toHaveCount(0);const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).setup());await page.getByRole('button',{name:'Далее',exact:true}).click();await page.getByRole('button',{name:'Подключить Phantom',exact:true}).click();await page.getByRole('button',{name:'Далее',exact:true}).click();await page.getByLabel('Адрес основной казны',{exact:true}).fill(v.config.wallets.service);await page.getByRole('button',{name:'Далее',exact:true}).click();await page.getByLabel('Адрес фонда',{exact:true}).fill(v.config.wallets.service);await expect(page.getByRole('button',{name:'Далее',exact:true})).toBeDisabled();await page.getByLabel('Адрес фонда',{exact:true}).fill(v.config.wallets.fund);await page.getByRole('button',{name:'Далее',exact:true}).click();await page.getByLabel('Адрес AR-резерва',{exact:true}).fill(v.config.wallets.arReserve);await page.getByRole('button',{name:'Далее',exact:true}).click();await expect(page.locator('.admin-summary')).toContainText('0.03 SOL');const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Подписать и создать конфигурацию',exact:true}).click();expect((await downloaded).suggestedFilename()).toBe('sejire-trust-anchor.json');const record=await page.evaluate(async()=>(await import('/src/lib/native/cache.ts')).readCache('trusted-session'));expect(record.chain.versions[0].signatures).toHaveLength(1);expect(record.chain.versions[0].acceptance).toHaveLength(1);const c=await browser.newContext(),p=await c.newPage();await fixtures(p);await p.goto('/#/admin');await importConfig(p,{config:record.chain.versions[0].config,chain:record.chain,anchor:record.trusted});await expect(p.getByRole('heading',{name:'Настроим SEJIRE'})).toHaveCount(0);expect(f.network.sends).toBe(0);await c.close();});
test('viewer cannot alter settings; advanced separate; owner confirms price in one action',async({page})=>{const f=await fixtures(page),v=await setup(page);await importConfig(page,v);await page.getByRole('button',{name:'Настройки',exact:true}).click();await expect(page.getByLabel('Цена сохранения (SOL)',{exact:true})).toBeDisabled();await expect(page.getByLabel('JSON конфигурации')).toHaveCount(0);await advanced(page);for(const name of ['Доверенный genesis SHA-256','JSON конфигурации','Solana RPC','Arweave узлы'])await expect(page.getByLabel(name,{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Проверить и применить подписанную версию',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Закрыть диагностику',exact:true}).click();await page.getByRole('button',{name:'Подтвердить управляющий Phantom',exact:true}).click();await page.getByLabel('Цена сохранения (SOL)',{exact:true}).fill('0.04');await page.getByLabel('Цена сохранения (SOL)',{exact:true}).blur();await expect(page.getByText('Изменения ещё не применены',{exact:true})).toBeVisible();page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Подтвердить изменения',exact:true}).click();await expect(page.getByRole('status')).toContainText('Настройки обновлены');expect((await page.evaluate(async()=>(await import('/src/lib/native/cache.ts')).readCache('trusted-session'))).chain.versions[1].config.serviceLamports).toBe('40000000');expect(f.network.sends).toBe(0);});
test('mobile setup finance advanced fit viewport',async({page})=>{await fixtures(page);await page.setViewportSize({width:390,height:844});await page.goto('/#/admin');await expect(page.getByRole('button',{name:'Далее',exact:true})).toBeVisible();await page.getByRole('button',{name:'Финансы',exact:true}).click();for(const name of ['Основная казна','Фонд памяти поколений','Резерв хранения'])await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await advanced(page);await expect(page.getByLabel('JSON конфигурации')).toBeVisible();});
test('missing wallet and rejected manager confirmation; account change revokes editor access',async({page})=>{await fixtures(page);await page.goto('/#/admin');await page.getByRole('button',{name:'Далее',exact:true}).click();await page.getByRole('button',{name:'Подключить Phantom',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Phantom не найден');const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).setup());await importConfig(page,v);await page.getByRole('button',{name:'Настройки',exact:true}).click();await page.evaluate(()=>window.fixtureWallet.rejectMessage=true);await page.getByRole('button',{name:'Подтвердить управляющий Phantom',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Подпись отменена');await expect(page.getByLabel('Цена сохранения (SOL)',{exact:true})).toBeDisabled();await page.evaluate(()=>window.fixtureWallet.rejectMessage=false);await page.getByRole('button',{name:'Подтвердить управляющий Phantom',exact:true}).click();await expect(page.getByLabel('Цена сохранения (SOL)',{exact:true})).toBeEnabled();await page.evaluate(()=>window.fixtureWallet.emit('accountChanged'));await expect(page.getByText('Режим просмотра',{exact:true})).toBeVisible();await expect(page.getByLabel('Цена сохранения (SOL)',{exact:true})).toBeDisabled();});
test('signed address rotation preserves old order and RPC payment recipients',async({page})=>{const f=await fixtures(page);await page.goto('/#/admin');const v=await page.evaluate(async()=>(await import('/tests/native-fixture.ts')).jobFixture(false,false));f.network.tx=v.tx;await importJob(page,v);await page.getByRole('button',{name:'Подтвердить управляющий Phantom',exact:true}).click();await page.getByRole('button',{name:'Финансы',exact:true}).click();const card=page.getByRole('article').filter({has:page.getByRole('heading',{name:'Основная казна',exact:true})});await card.getByRole('button',{name:'Заменить адрес',exact:true}).click();const next=bs58.encode(new Uint8Array(32).fill(4));await page.getByLabel('Новый публичный адрес Основная казна',{exact:true}).fill(next);page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Подтвердить изменения',exact:true}).click();await expect(page.getByRole('status')).toContainText('Настройки обновлены');await page.getByRole('button',{name:'Сохранения',exact:true}).click();await expect(page.getByText('Оплата проверена',{exact:true})).toBeVisible();const stored=await page.evaluate(async()=>({record:await(await import('/src/lib/native/cache.ts')).readCache('trusted-session'),jobs:await(await import('/src/lib/native/cache.ts')).cachedJobs()}));expect(stored.record.chain.versions[1].config.wallets.service).toBe(next);expect(stored.jobs[0].order.servicePayment.recipient).toBe(v.config.wallets.service);expect(stored.jobs[0].order).toEqual(v.job.order);expect(f.network.sends).toBe(0);});
test('network failure never invents a treasury balance or global network failure',async({page})=>{await fixtures(page);const v=await setup(page);await importConfig(page,v);await page.route('https://api.devnet.solana.com*',route=>route.fulfill({status:429,body:'rate limited'}));await page.getByRole('button',{name:'Проверить состояние системы',exact:true}).click();await expect(page.locator('.admin-status')).toContainText('Некоторые данные недоступны');await expect(page.getByRole('region',{name:'Баланс основной казны',exact:true})).toContainText('Нет данных');});
test('public balances never wait for history and history failure preserves them',async({page})=>{
 await fixtures(page);const v=await setup(page);await importConfig(page,v);let history=0;
 await page.route('https://api.devnet.solana.com*',async route=>{const p=route.request().postDataJSON();if(p.method==='getSignaturesForAddress'){history++;return;}await route.fallback();});
 await page.getByRole('button',{name:'Проверить состояние системы',exact:true}).click();const card=page.getByRole('region',{name:'Баланс основной казны',exact:true});await expect(card).toContainText('1 SOL');expect(history).toBe(0);
 await advanced(page);await page.getByRole('button',{name:'Загрузить историю основной казны',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Сеть не ответила вовремя',{timeout:15000});await page.getByRole('button',{name:'Обзор',exact:true}).click();await expect(card).toContainText('1 SOL');expect(history).toBe(1);
});
test('HTTP 429 is diagnosed separately; other treasury and AR remain visible',async({page})=>{
 await fixtures(page);const v=await setup(page);await importConfig(page,v);
 await page.route('https://api.devnet.solana.com*',async route=>{const p=route.request().postDataJSON();if(p.method==='getBalance'&&p.params[0]===v.config.wallets.service)return route.fulfill({status:429,headers:{'Retry-After':'60'},body:'rate limited'});await route.fallback();});
 await page.getByRole('button',{name:'Проверить состояние системы',exact:true}).click();await expect(page.getByRole('region',{name:'Баланс фонда',exact:true})).toContainText('1 SOL');await expect(page.getByRole('article',{name:'Баланс резерва хранения',exact:true})).toContainText('0.0000001 AR');await expect(page.getByText('Не удалось обновить один из балансов Solana. Прежние данные не удалены.',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Баланс основной казны',exact:true})).toContainText('Нет данных');await advanced(page);await expect(page.locator('pre').filter({hasText:'diagnostics'})).toContainText('429');
});
test('wrong genesis rejects SOL balances without hiding AR',async({page})=>{
 await fixtures(page);const v=await setup(page);await importConfig(page,v);let balances=0;
 await page.route('https://api.devnet.solana.com*',async route=>{const p=route.request().postDataJSON();if(p.method==='getBlockHeight')result=100;
 else if(p.method==='getGenesisHash')return route.fulfill({json:{jsonrpc:'2.0',id:p.id,result:'wrong-genesis'}});if(p.method==='getBalance')balances++;await route.fallback();});
 await page.getByRole('button',{name:'Проверить состояние системы',exact:true}).click();await expect(page.locator('.admin-status')).toContainText('Некоторые данные недоступны');await expect(page.getByRole('region',{name:'Баланс основной казны',exact:true})).toContainText('Нет данных');await expect(page.getByRole('article',{name:'Баланс резерва хранения',exact:true})).toContainText('0.0000001 AR');expect(balances).toBe(0);
});
test('real deadline reports timeout; second balance appears before timeout; stale value is marked',async({page})=>{
 await fixtures(page);const v=await setup(page);await importConfig(page,v);await page.getByRole('button',{name:'Проверить состояние системы',exact:true}).click();const service=page.getByRole('region',{name:'Баланс основной казны',exact:true});await expect(service).toContainText('1 SOL');await expect(page.getByRole('button',{name:'Проверить состояние системы',exact:true})).toBeEnabled();
 await page.route('https://api.devnet.solana.com*',async route=>{const p=route.request().postDataJSON();if(p.method==='getBalance'&&p.params[0]===v.config.wallets.service)return;await route.fallback();});await page.getByRole('button',{name:'Проверить состояние системы',exact:true}).click();await expect(page.getByRole('region',{name:'Баланс фонда',exact:true})).toContainText('1 SOL');await expect(service).toContainText('обновить не удалось',{timeout:25000});await expect(service).toContainText('1 SOL');await expect(service).toContainText('обновить не удалось');
});
