import {test,expect} from '@playwright/test';
async function offline(page){const posts=[];await page.route('**/*',async r=>{const u=new URL(r.request().url());if(['https://arweave.net/graphql','https://arweave-search.goldsky.com/graphql','https://ar-io.dev/graphql'].includes(u.href)){const body=r.request().postDataJSON();expect(r.request().method()).toBe('POST');expect(body.query.trim()).toMatch(/^query\b/);return r.fulfill({json:{data:{transactions:{edges:[]}}}});}if(!['127.0.0.1','localhost'].includes(u.hostname)){posts.push(r.request().url());return r.abort();}return r.continue();});await page.addInitScript(()=>localStorage.setItem('sejire.locale','ru'));return posts;}
test('pilot build keeps viewer permissions and config publication closed',async({page})=>{
 const posts=await offline(page);await page.goto('/#/admin');await expect(page.getByText('Режим просмотра',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Настройки',exact:true}).click();await expect(page.getByRole('button',{name:'Подготовить это сохранение',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Диагностика разработчика',exact:true}).click();await expect(page.getByRole('button',{name:'Опубликовать конфигурацию в Arweave (сейчас отключено)',exact:true})).toBeDisabled();expect(posts).toEqual([]);
});
test('stopped executor prevents order signature; wrong imported archive cannot replace ciphertext',async({page})=>{
 const posts=await offline(page);await page.goto('/');const v=await page.evaluate(async()=>{const mod=await import('/tests/native-fixture.ts');const v=await mod.stoppedSetup();await(await import('/src/lib/native/session.ts')).trustChain(v.chain,v.anchor);return v;});
 await page.getByRole('button',{name:'Открыть по 12 словам',exact:true}).click();await page.getByRole('button',{name:'Открыть из файла',exact:true}).click();await page.locator('input[type=file]').setInputFiles({name:'archive.json',mimeType:'application/json',buffer:Buffer.from(v.family.serialized)});await page.getByRole('textbox',{name:'12 слов восстановления SEJIRE'}).fill(v.family.words);await page.getByRole('button',{name:'Восстановить архив',exact:true}).click();await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();await page.getByRole('button',{name:'Сохранить через Solana',exact:true}).click();
 await page.evaluate(()=>{window.orderSignatures=0;const w=window.phantom.solana,old=w.signMessage;w.signMessage=(...args)=>{window.orderSignatures++;return old(...args);};});await expect(page.getByRole('button',{name:'Продолжить с Phantom',exact:true})).toBeDisabled();await expect(page.getByRole('note')).toContainText('Сохранение временно недоступно');expect(await page.evaluate(()=>window.orderSignatures)).toBe(0);await expect(page.getByRole('button',{name:/^Оплатить /})).toHaveCount(0);
 const rejected=await page.evaluate(async()=>{try{await(await import('/src/lib/native/pilot.ts')).importPilotArchive(new File(['{}'],'wrong.json'));return false;}catch{return true;}});expect(rejected).toBe(true);expect(posts).toEqual([]);
});
test('pilot low-level signing and broadcast reject unrelated bytes without touching wallets or nodes',async({page})=>{
 const posts=await offline(page);await page.goto('/');const result=await page.evaluate(async()=>{const {signNative,uploadNative}=await import('/src/lib/native/arweave.ts');const {PILOT}=await import('/src/lib/native/pilot.ts');let walletCalls=0;const wallet={getActiveAddress:async()=>{walletCalls++;return PILOT.address;}};const errors=[];try{await signNative(['https://arweave.net'],wallet,PILOT.address,'{}',[{name:'Type',value:'configuration'}],PILOT.maximum);}catch(e){errors.push(e.message);}try{await uploadNative(['https://arweave.net'],{address:PILOT.address,rewardWinston:PILOT.maximum},'{}',[],async()=>{},false);}catch(e){errors.push(e.message);}return {errors,walletCalls};});expect(result.errors).toEqual(['archive_not_authorized_for_pilot','archive_not_authorized_for_pilot']);expect(result.walletCalls).toBe(0);expect(posts).toEqual([]);
});
