import {devnetSuccessor,linkedSuccessor,prePaymentOnly,assertReplacement} from '../lib/native/successor';
import {recordSavingError,type SavingStage} from '../lib/native/diagnostics';
import { savingState, canStartDevnetRiskTest } from '../lib/native/presentation';
import { parseEnvelope, serializeEnvelope } from '../lib/crypto/envelope';
import { envelopeDigest } from '../lib/solana/policy';
import { findPaymentByReference } from '../lib/native/rpc';
import { nativeStatus, retrieveNative } from '../lib/native/arweave';
import { pilotEnabled, nativeMessage, PILOT } from '../lib/native/pilot';
import { useEffect, useState, useRef } from 'react';
import type { EnvelopeV1 } from '../lib/crypto/encrypt';
import { downloadEnvelope } from '../lib/crypto/vault';
import { downloadJson } from '../lib/download';
import { cachedChain, cachedJobs, saveJob, readCache, writeCache } from '../lib/native/cache';
import { nativeSession, trustChain, restoreNativeSession, restoreJobSession } from '../lib/native/session';
import { type ConfigChain } from '../lib/native/config';
import { configForJob, newJob, reconcileJob, validateJob, readyForOrder, type NativeJob } from '../lib/native/jobs';
import { solWallet, preparePayment, signAndBroadcast, resumeSignedPayment } from '../lib/native/payment';
import { formatAmount, parseAmount, requiresLargeAmountConfirmation } from '../../../../packages/checkout/amounts';
export function NativeCheckoutPanel({envelope,onBack,onBusy,treeName,recoveryKeyInMemory=false,resume=false}:{resume?:boolean;envelope?:EnvelopeV1;treeName?:string;recoveryKeyInMemory?:boolean;onBack:()=>void;onBusy?:(value:boolean)=>void}) {
 const [selectedEnvelope,setSelectedEnvelope]=useState(envelope);
 const [orphan,setOrphan]=useState(false);
 const archive=selectedEnvelope;
 const [chain,setChain]=useState<ConfigChain|undefined>(nativeSession()?.chain),[anchor,setAnchor]=useState(nativeSession()?.trusted??''),[contribution,setContribution]=useState('0'),[job,setJob]=useState<NativeJob>(),[pending,setPending]=useState<NativeJob[]>([]);
 const [prepared,setPrepared]=useState<Awaited<ReturnType<typeof preparePayment>>>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[consent,setConsent]=useState(false);
 const [paid,setPaid]=useState(false),[stored,setStored]=useState(false),[phase,setPhase]=useState('Подготовка'),[initialized,setInitialized]=useState(false),[availability,setAvailability]=useState<'checking'|'ready'|'unavailable'>('checking');
 const [cleanDemoId,setCleanDemoId]=useState<string>();
 const c=nativeSession()?.config;
 const display=savingState(job,paid,stored);
 const cleanDemoAvailable=Boolean(pilotEnabled()&&c?.environment==='devnet'&&archive&&job?.signingStarted&&!job.paymentSignature&&!job.reconciledSignature&&job.order.archive?.digest===PILOT.digest&&job.order.archive.bytes===PILOT.bytes&&job.order.id!==cleanDemoId);
 useEffect(()=>{void readCache<string>('clean-demo-order').then(v=>{if(v)setCleanDemoId(v);}).catch(()=>{});},[]);
 useEffect(()=>{let live=true;(async()=>{const restored=await restoreNativeSession();if(restored&&live){setChain(restored.chain);setAnchor(restored.trusted);}else if(live)setChain(await cachedChain());const jobs=await cachedJobs();const requested=new URLSearchParams(location.hash.split('?')[1]??'').get('order');const found=requested?jobs.find(j=>j.order.id===requested):undefined;if(live){setPending(jobs);if(found&&restored){stageOrder.current=found.order.id;markStage('successor_restore');setJob(found);let exact=restored;try{exact=await restoreJobSession(found);}catch(e){if(e instanceof Error&&e.message==='unknown_order_configuration')setOrphan(prePaymentOnly(found));throw e;}setChain(exact.chain);const cfg=await configForJob(exact.chain,found,exact.trusted);await validateJob(found,cfg);if(found.attempt?.phase==='wallet_pending'){found.attempt.phase='signature_unknown';await saveJob(found);}setJob(found);if(found.ciphertext)setSelectedEnvelope(parseEnvelope(JSON.parse(found.ciphertext)));if(found.signingStarted)setStatus('Результат прежней подписи требует проверки. Повторная оплата заблокирована.');}else if(envelope||resume){const draft=await readCache<string>('saving-ciphertext');if(draft){const previous=parseEnvelope(JSON.parse(draft));if(!envelope||previous.vault_id===envelope.vault_id){setSelectedEnvelope(previous);if(envelope&&draft!==serializeEnvelope(envelope))setStatus('Продолжаем ранее подготовленный архив. Его байты сохранены; новые правки редактора не включаются в эту попытку.');}}}setInitialized(true);}})().catch(e=>{if(live){void recordSavingError(stage.current,e,stageOrder.current);setError(nativeMessage(e.message));setInitialized(true);}});return()=>{live=false;};},[]);
 useEffect(()=>{if(initialized&&archive)void writeCache('saving-ciphertext',serializeEnvelope(archive)).catch(()=>setError('Не удалось сохранить архив на устройстве. Скачайте резервную копию; оплата не начата.'));},[archive,initialized]);
 useEffect(()=>{let live=true;setAvailability('checking');if(!initialized)return()=>{live=false;};if(!c){setAvailability('unavailable');return()=>{live=false;};}if(job){setAvailability('ready');return()=>{live=false;};}if(!archive){setAvailability('ready');return()=>{live=false;};}const bytes=serializeEnvelope(archive);void envelopeDigest(bytes).then(digest=>readyForOrder(c,new TextEncoder().encode(bytes).length,digest)).then(()=>{if(live)setAvailability('ready');}).catch(()=>{if(live)setAvailability('unavailable');});return()=>{live=false;};},[initialized,c,archive,job?.order.id]);
 const lock=useRef(false),stage=useRef<SavingStage>('reconcile_previous'),stageOrder=useRef<string|undefined>(undefined);
 const markStage=(value:SavingStage)=>{stage.current=value;if(value==='order_signature'){setPhase('Подтверждение в кошельке');setStatus('Подтвердите создание сохранения. Эта подпись создаёт защищённый заказ и не переводит средства.');}};
 async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);onBusy?.(true);setError('');setStatus('');try{await action();}catch(e){await recordSavingError(stage.current,e,stageOrder.current??job?.order.id);setPhase('Подготовка');setError(nativeMessage(e&&typeof e==='object'&&'code'in e&&e.code===4001?'signature_cancelled':e instanceof Error?e.message:'requires_reconciliation'));if(e instanceof Error&&e.message==='cache_commit_failed'&&job?.signedPayment&&job.paymentSignature)downloadJson({schema:'sejire/native-job-package/v1',chain,job},`sejire-pending-${job.order.id}.json`);}finally{lock.current=false;setBusy(false);onBusy?.(false);}}
 async function authorize(){const latest=nativeSession();const candidate=latest?.trusted===anchor&&(!chain||latest.chain.versions.length>chain.versions.length)?latest.chain:chain;if(!candidate)throw Error('signed_configuration_required');const session=await trustChain(candidate,anchor);setChain(session.chain);return session;}
 async function create(){if(pilotEnabled()&&archive){if(parseAmount(contribution,9)!=='0')throw Error('Для этого пилота добровольный взнос должен быть 0 SOL');const old=(await cachedJobs()).find(j=>j.order.archive?.digest==='19133b897f69e1f0d43a55217a00adee6b6dfefb73f0f6228008f5c8a702e6c8');if(old)throw Error('Прежний заказ этого архива уже сохранён. Выберите его для продолжения, не создавайте новую оплату.');}const s=await authorize();if(archive)await readyForOrder(s.config,new TextEncoder().encode(serializeEnvelope(archive)).length,await envelopeDigest(serializeEnvelope(archive)));setPhase('Подтверждение в кошельке');const wallet=solWallet();await wallet.connect();if(!wallet.publicKey)throw Error('wallet_not_connected');const units=parseAmount(contribution,9);if(requiresLargeAmountConfirmation(units,'100000000000')&&!window.confirm(`Добровольный вклад ${formatAmount(units,9)} SOL. Проверьте сумму и адрес фонда ${s.config.wallets.fund}.`))return;
 const next=await newJob(s.config,wallet.publicKey.toString(),contribution,archive,wallet,undefined,markStage);markStage('successor_persist');await saveJob(next);await writeCache('active-saving',next.order.id);setJob(next);history.replaceState(null,'',`#/save?order=${next.order.id}`);markStage('payment_prepare');setPrepared(await preparePayment(s.config,next));setPhase('Подтверждение в кошельке');setStatus('Подтвердите оплату в Phantom. Заказ уже подтверждён без списания.');}
 async function reconcile(value:NativeJob|undefined=job){if(!value)throw Error('select_order');value=(await cachedJobs()).find(j=>j.order.id===value!.order.id)??value;setPhase('Проверка оплаты');const session=await authorize(),cfg=await configForJob(session.chain,value,session.trusted);
 if(!value.paymentSignature&&!value.reconciledSignature){const found=await findPaymentByReference(cfg,value.order);if(found.signature){value.reconciledSignature=found.signature;await saveJob(value);}else{setJob({...value});setStatus('Подтверждённая оплата пока не найдена. Это не доказывает, что списания не было. Прежняя попытка остаётся в истории; автоматически повторять оплату нельзя.');return;}}
 let result:Awaited<ReturnType<typeof reconcileJob>>|undefined;for(let retry=0;retry<3;retry++){try{result=await reconcileJob(value,cfg,await cachedJobs());break;}catch(e){const error=e as Error&{details?:{retryAfterMs?:number}};if(error.message==='transaction_failed'&&(paid||value.arPlan||value.attempt?.phase==='finalized'))throw Error('conflicting_payment_result');if(error.message==='transaction_failed'&&value.attempt){value.attempt.phase='failed';await saveJob(value);}const delay=error.details?.retryAfterMs??(500*(retry+1));if(retry===2||delay>2000||!['requires_reconciliation','rpc-timeout','rpc-unavailable','rpc-rate-limited'].includes(error.message))throw e;await new Promise(resolve=>setTimeout(resolve,delay));}}if(!result)throw Error('requires_reconciliation');setPaid(true);if(value.attempt)value.attempt.phase='finalized';await saveJob(value);setJob({...value});setPhase(value.order.archive?'Ожидает исполнителя':'Проверка оплаты');setStatus(value.order.archive?'Оплата подтверждена. Ваше дерево ожидает сохранения. Оператор видит его на этом устройстве.':'Оплата подтверждена. Спасибо, Хранитель памяти.');
 if(value.arPlan){setPhase(value.arPlan.uploaded?'Проверка сохранения':'Отправка архива');const state=await nativeStatus(cfg.arweaveNodes,value.arPlan.id);if(state.status===200&&state.confirmed){const retrieved=await retrieveNative(cfg.arweaveNodes,value.arPlan.id,value.order.archive!.digest,value.order.archive!.bytes);await writeCache('retrieved-saving',{id:value.arPlan.id,serialized:retrieved.text});setStored(true);setStatus('Семейная история сохранена. Полученный архив проверен. Открыть его можно с вашими словами SEJIRE.');}}
 }
 async function successor(previous:NativeJob){const session=await authorize(),wallet=solWallet();await wallet.connect();const next=await newJob(session.config,wallet.publicKey!.toString(),formatAmount(previous.order.fundContribution.amount,9),archive,wallet,previous.order.id);await saveJob(next);await writeCache('active-saving',next.order.id);setPaid(false);setStored(false);setConsent(false);setJob(next);setPrepared(undefined);history.replaceState(null,'',`#/save?order=${next.order.id}`);stageOrder.current=next.order.id;markStage('payment_prepare');setPrepared(await preparePayment(session.config,next));setStatus('Новый заказ связан с прежним. Проверьте сумму перед подписью платежа.');}
 async function startRiskTest(){if(!job)throw Error('devnet_risk_test_not_allowed');return startRiskTestFor(job);}
 async function startRiskTestFor(previous:NativeJob){stageOrder.current=previous.order.id;
let session=await authorize();const linked=linkedSuccessor(await cachedJobs(),previous);let replacement:NativeJob|undefined;
 if(linked){stageOrder.current=linked.order.id;markStage('successor_restore');
  try{session=await restoreJobSession(linked);setChain(session.chain);const cfg=await configForJob(session.chain,linked,session.trusted);await validateJob(linked,cfg);setJob(linked);setPrepared(undefined);setConsent(false);await writeCache('active-saving',linked.order.id);location.hash=`#/save?order=${linked.order.id}`;setStatus('Продолжаем ваше сохранение. Прежняя попытка остаётся в истории.');return;}
  catch(e){await recordSavingError('successor_restore',e,linked.order.id);if(!(e instanceof Error)||e.message!=='unknown_order_configuration')throw e;await assertReplacement(previous,linked);replacement=linked;
   if(!window.confirm('Предыдущая подготовка не завершилась. В этой записи оплата не начиналась. Подготовить новое тестовое сохранение? История останется сохранена. Прежний неизвестный платёж не опровергнут; оплата нового теста потребует отдельного подтверждения.'))return;
  }
 }
 if(session.config.environment!=='devnet'||!canStartDevnetRiskTest(previous))throw Error('devnet_risk_test_not_allowed');
 stageOrder.current=previous.order.id;markStage('reconcile_previous');const previousConfig=await configForJob(session.chain,previous,session.trusted);try{const found=await findPaymentByReference(previousConfig,previous.order);if(found.signature){previous.reconciledSignature=found.signature;await saveJob(previous);setJob(previous);await reconcile(previous);return;}}catch(e){if(!(e instanceof Error)||!['rpc-timeout','rpc-rate-limited','rpc-unavailable','requires_reconciliation'].includes(e.message))throw e;}
 if(!replacement&&!window.confirm('Результат прежней попытки неизвестен. Новый тест может дополнительно списать 0,03 тестового SOL и сетевую комиссию. Прежняя попытка останется в истории. Начать новый тест?'))return;

 const next=await devnetSuccessor(session,previous,solWallet(),markStage,replacement);stageOrder.current=next.order.id;markStage('route_switch');setOrphan(false);setPaid(false);setStored(false);setConsent(false);setJob(next);setPrepared(undefined);await writeCache('active-saving',next.order.id);history.replaceState(null,'',`#/save?order=${next.order.id}`);setPending(await cachedJobs());markStage('payment_prepare');const cfg=await configForJob(session.chain,next,session.trusted);setPrepared(await preparePayment(cfg,next));setStatus('Теперь подтвердите оплату. Создание сохранения завершено без перевода средств.');
 }
 async function startCleanDevnetDemo(){
  if(!archive)throw Error('archive_binding');
  const serialized=serializeEnvelope(archive),digest=await envelopeDigest(serialized),bytes=new TextEncoder().encode(serialized).length;
  if(digest!==PILOT.digest||bytes!==PILOT.bytes)throw Error('archive_not_authorized_for_pilot');
  const session=await authorize();if(session.config.environment!=='devnet')throw Error('devnet_risk_test_not_allowed');
  await readyForOrder(session.config,bytes,digest);
  if(!navigator.locks)throw Error('exclusive_browser_lock_unavailable');
  await navigator.locks.request('sejire-clean-devnet-demo',async()=>{
   const jobs=await cachedJobs(),remembered=await readCache<string>('clean-demo-order');
   if(remembered){
    const existing=jobs.find(j=>j.order.id===remembered);
    if(existing){
     stageOrder.current=existing.order.id;markStage('successor_restore');
     const exact=await restoreJobSession(existing);setChain(exact.chain);const cfg=await configForJob(exact.chain,existing,exact.trusted);await validateJob(existing,cfg);
     setCleanDemoId(existing.order.id);setJob(existing);setPaid(false);setStored(false);setConsent(false);setPrepared(undefined);if(existing.ciphertext)setSelectedEnvelope(parseEnvelope(JSON.parse(existing.ciphertext)));
     await writeCache('active-saving',existing.order.id);history.replaceState(null,'',`#/save?order=${existing.order.id}`);setPending(jobs);
     if(!existing.signingStarted&&!existing.paymentSignature&&!existing.reconciledSignature){markStage('payment_prepare');setPrepared(await preparePayment(cfg,existing));setStatus('Чистое тестовое сохранение уже подготовлено. Проверьте сумму перед оплатой.');}
     else setStatus('Продолжаем чистое тестовое сохранение. Новая оплата автоматически не создаётся.');
     return;
    }
   }
   if(!window.confirm('Предыдущие DEVNET-попытки останутся в истории и больше не будут продолжаться. Новый чистый тест может дополнительно использовать 0.03 тестового SOL и сетевую комиссию. Реальные SOL не используются. Начать чистое тестовое сохранение?'))return;
   markStage('wallet_connect');const wallet=solWallet();await wallet.connect();const payer=wallet.publicKey?.toString();if(!payer)throw Error('wallet_not_connected');if(!session.config.managers.includes(payer))throw Error('manager_not_authorized');
   const next=await newJob(session.config,payer,'0',archive,wallet,undefined,markStage);stageOrder.current=next.order.id;markStage('successor_persist');await saveJob(next);await writeCache('clean-demo-order',next.order.id);await writeCache('active-saving',next.order.id);
   setCleanDemoId(next.order.id);setPaid(false);setStored(false);setConsent(false);setJob(next);setPrepared(undefined);history.replaceState(null,'',`#/save?order=${next.order.id}`);setPending(await cachedJobs());
   markStage('payment_prepare');setPrepared(await preparePayment(session.config,next));setStatus('Чистое тестовое сохранение создано. Первая подпись была без перевода средств. Проверьте сумму перед оплатой.');
  });
 }
 async function primary(){if(cleanDemoAvailable){await startCleanDevnetDemo();return;}if(job&&orphan){const previous=(await cachedJobs()).find(j=>j.order.id===job.supersedes);if(!previous)throw Error('previous_payment_requires_reconciliation');await startRiskTestFor(previous);return;}if(job&&linkedSuccessor(pending,job)){await startRiskTest();return;}if(stored){location.hash='#/restore?saved=1';return;}if(!job){await create();return;}if(job.paymentSignature||job.reconciledSignature||job.signingStarted){try{await reconcile();}catch(e){if(e instanceof Error&&e.message==='transaction_failed'&&job.signedPayment){if(window.confirm('Выбранный RPC подтвердил неуспешную finalized-транзакцию. Создать связанный новый заказ? Комиссия прежней попытки не возвращается; новая оплата потребует вашего отдельного подтверждения.'))await successor(job);else setStatus('Прежняя finalized-транзакция неуспешна. Новый заказ не создан; подпись остаётся в истории.');}else if(e instanceof Error&&e.message==='requires_reconciliation'&&job.signedPayment&&job.attempt){const current=await authorize(),cfg=await configForJob(current.chain,job,current.trusted);await resumeSignedPayment(cfg,job);await reconcile();}else throw e;}return;}const session=await authorize(),cfg=await configForJob(session.chain,job,session.trusted);if(job.order.expiresAt<=Date.now()||Boolean(job.order.archive&&cfg.upload.acceptingUntil<=Date.now())){if(job.signingStarted||job.paymentSignature||job.reconciledSignature)throw Error('previous_payment_requires_reconciliation');if(!window.confirm('Срок прежнего заказа или готовности исполнителя истёк до подписи платежа. Создать связанный новый заказ с текущими условиями? Прежний заказ останется в истории.'))return;await successor(job);return;}if(!prepared){setPrepared(await preparePayment(cfg,job));setStatus('Подготовка обновлена. Проверьте актуальную комиссию и подтвердите платёж.');return;}if(!consent)throw Error('exact_consent_required');const fresh=await preparePayment(cfg,job);setPrepared(fresh);if(prepared.feeLamports!==fresh.feeLamports){setConsent(false);setStatus('Комиссия изменилась. Проверьте сумму и подтвердите ещё раз.');return;}const wallet=solWallet();await wallet.connect();try{await signAndBroadcast(cfg,job,wallet,fresh,import.meta.env.VITE_NATIVE_SOL_MAINNET==='1');}catch(e){setJob({...job});if(job.paymentSignature){await reconcile(job);return;}throw e;}setPrepared(undefined);setJob({...job});await reconcile(job);}
 const checked=useRef('');useEffect(()=>{if(initialized&&job&&(job.paymentSignature||job.reconciledSignature)&&checked.current!==job.order.id){checked.current=job.order.id;void run(()=>reconcile(job));}},[initialized,job?.order.id]);
 async function operator(){if(archive)await writeCache('saving-ciphertext',serializeEnvelope(archive));if(job)await writeCache('active-saving',job.order.id);location.hash=job?`#/admin?order=${job.order.id}`:'#/admin?prepare=1';}
 return <section className="checkout-panel saving-screen" aria-label="Сохранение семейной истории"><h3>{archive?'Сохранить семейную историю':'Помочь другим семьям'}</h3>
 <section className="saving-summary"><h4>{treeName??(archive?'Семейная история':'Фонд памяти поколений SEJIRE')}</h4>
 {archive&&<p>Данные зашифрованы. Для восстановления понадобятся ваши 12 слов SEJIRE. Это отдельный ключ семейного архива, не слова кошелька Phantom или Wander.</p>}
 <small>{archive&&recoveryKeyInMemory?'Ключ подготовлен в этом сеансе. Храните слова отдельно.':archive?'Для открытия понадобятся ранее сохранённые слова SEJIRE.':'Ключ семейного архива не требуется.'}</small>
 <p>Оплата SOL — {c?.environment==='devnet'?'тестовая сеть':c?'основная сеть; оплата выключена':'проект ещё не активирован'}.</p><p>Хранение AR — основная сеть, реальные средства оператора. Arweave — независимое хранилище семейных архивов.</p>
 <dl className="saving-total"><dt>Сохранение</dt><dd>{formatAmount(job?.order.servicePayment.amount??(archive?c?.serviceLamports??'30000000':'0'),9)} SOL</dd><dt>Комиссия сети</dt><dd>{prepared?formatAmount(prepared.feeLamports,9)+' SOL':'Уточним перед оплатой'}</dd></dl>
 {!job&&<label>Помочь другим семьям (SOL)<input aria-label="Добровольный вклад SOL" value={contribution} inputMode="decimal" onChange={e=>{setContribution(e.target.value);setConsent(false);}}/></label>}
 {job&&<p>Помочь другим семьям: {formatAmount(job.order.fundContribution.amount,9)} SOL</p>}
 <p><strong>Итого: {job?formatAmount(job.order.total,9):(()=>{try{return formatAmount((BigInt(archive?c?.serviceLamports??'30000000':'0')+BigInt(parseAmount(contribution,9))).toString(),9);}catch{return 'Проверьте сумму';}})()} SOL + комиссия сети</strong></p>
 {!job&&<p>Подтвердите создание сохранения. Следующий запрос Phantom создаёт защищённый заказ и не переводит средства.</p>}{prepared&&!paid&&!job?.signingStarted&&<h4>Теперь подтвердите оплату</h4>}
 <p className="saving-stage">{display.label}</p><ol className="admin-progress saving-progress" aria-label="Ход сохранения"><li>{paid?'✓':job?.signingStarted&&!job.paymentSignature?'○':'→'} Оплата</li><li>{stored?'✓':paid?'→':'○'} Сохранение</li><li>{stored?'✓':'○'} Готово</li></ol>
 {busy&&<p aria-live="polite">{phase==='Подтверждение в кошельке'?'Проверьте окно Phantom. Подтверждение заказа не списывает деньги; оплата подтверждается отдельно.':'Проверяем сохранённую операцию. Закрытие экрана не отменяет её.'}</p>}
 {prepared&&!paid&&!job?.signingStarted&&!job?.paymentSignature&&<label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Подтверждаю показанные суммы и сеть</label>}
 {availability==='unavailable'&&!job&&<p role="note">Сохранение временно недоступно. Ваше дерево не потеряно. Попробуйте немного позже или скачайте резервную копию.</p>}
 <button className="btn saving-primary" disabled={busy||!initialized||!c||(!job&&availability!=='ready')||Boolean(paid&&!archive)||Boolean(prepared&&!paid&&!job?.signingStarted&&!consent)} onClick={()=>void run(primary)}>{cleanDemoAvailable?'Начать чистое тестовое сохранение':job&&(orphan||pending.some(j=>j.supersedes===job.order.id))?'Продолжить':stored?'Открыть дерево':!job?'Продолжить с Phantom':paid||job.signingStarted||job.paymentSignature||!prepared?'Продолжить сохранение':`Оплатить ${formatAmount(job.order.total,9)} SOL`}</button>
 {!job&&availability==='checking'&&<p>Проверяем возможность сохранить этот архив…</p>}
 {archive&&<button className="btn ghost" onClick={()=>downloadEnvelope(archive)}>Скачать резервную копию</button>}
 {job&&pending.some(j=>j.supersedes===job.order.id)&&<p>Предыдущая попытка сохранена.</p>}{orphan&&<p>Подготовка нового сохранения не завершилась. В этой записи оплата не начиналась.</p>}
 {job?.signingStarted&&!job.paymentSignature&&!job.reconciledSignature&&<section className="saving-uncertain"><h4>Предыдущее сохранение не завершилось</h4><p>Результат подтверждения неизвестен. Проверка оплаты не запускает новый платёж.</p>{!job.attempt&&<p>В старой записи не хватает данных, чтобы безопасно установить завершение попытки.</p>}{cleanDemoAvailable&&<p>Старые DEVNET-попытки останутся в истории. Для текущего разрешённого архива можно начать один новый чистый тест.</p>}{canStartDevnetRiskTest(job)&&!cleanDemoAvailable&&!pending.some(j=>j.supersedes===job.order.id)&&<button className="btn ghost" disabled={busy} onClick={()=>void run(startRiskTest)}>Начать новый тест</button>}</section>}
 {paid&&!stored&&job?.order.archive&&<p>Для владельца-оператора: <button className="btn ghost" onClick={()=>void run(operator)}>Открыть это сохранение в админке</button>. На другом устройстве автоматической очереди пока нет.</p>}
 </section>
 <details className="saving-details"><summary>Подробнее</summary><p>Оплата проходит через Solana. Зашифрованная семейная история сохраняется в Arweave. Ваши 12 слов SEJIRE не передаются Phantom, Arweave или оператору.</p></details>
 <a className="saving-owner-link" href={job?`#/admin?order=${job.order.id}`:'#/admin'}>Открыть панель владельца</a>
 {error&&<p role="alert">{error}</p>}{status&&<p role="status">{status}</p>}<button className="btn ghost" disabled={busy} onClick={onBack}>Назад</button></section>;
}
