import { nativeReceipt } from '../lib/native/receipt';
import { parseEnvelope, serializeEnvelope } from '../lib/crypto/envelope';
import { envelopeDigest } from '../lib/solana/policy';
import { findPaymentByReference } from '../lib/native/rpc';
import { nativeStatus, retrieveNative } from '../lib/native/arweave';
import { pilotEnabled, importPilotArchive, nativeMessage } from '../lib/native/pilot';
import { useEffect, useState, useRef } from 'react';
import type { EnvelopeV1 } from '../lib/crypto/encrypt';
import { downloadEnvelope } from '../lib/crypto/vault';
import { downloadJson } from '../lib/download';
import { cachedChain, cachedJobs, saveJob, readCache, writeCache } from '../lib/native/cache';
import { nativeSession, trustChain, restoreNativeSession } from '../lib/native/session';
import { type ConfigChain } from '../lib/native/config';
import { configForJob, newJob, reconcileJob, validateJob, readyForOrder, type NativeJob } from '../lib/native/jobs';
import { solWallet, preparePayment, signAndBroadcast, resumeSignedPayment } from '../lib/native/payment';
import { formatAmount, parseAmount, requiresLargeAmountConfirmation } from '../../../../packages/checkout/amounts';
export function NativeCheckoutPanel({envelope,onBack,onBusy,treeName,resume=false}:{resume?:boolean;envelope?:EnvelopeV1;treeName?:string;onBack:()=>void;onBusy?:(value:boolean)=>void}) {
 const [selectedEnvelope,setSelectedEnvelope]=useState(envelope);
 const archive=selectedEnvelope;
 const [chain,setChain]=useState<ConfigChain|undefined>(nativeSession()?.chain),[anchor,setAnchor]=useState(nativeSession()?.trusted??''),[contribution,setContribution]=useState('0'),[job,setJob]=useState<NativeJob>(),[pending,setPending]=useState<NativeJob[]>([]);
 const [prepared,setPrepared]=useState<Awaited<ReturnType<typeof preparePayment>>>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[consent,setConsent]=useState(false);
 const [paid,setPaid]=useState(false),[stored,setStored]=useState(false),[phase,setPhase]=useState('Подготовка'),[initialized,setInitialized]=useState(false);
 const c=nativeSession()?.config;
 useEffect(()=>{let live=true;(async()=>{const restored=await restoreNativeSession();if(restored&&live){setChain(restored.chain);setAnchor(restored.trusted);}else if(live)setChain(await cachedChain());const jobs=await cachedJobs();const focus=await readCache<string>('active-saving');const requested=new URLSearchParams(location.hash.split('?')[1]??'').get('order');const found=jobs.find(j=>j.order.id===(requested??focus)&&(requested||resume||(envelope?j.ciphertext&&parseEnvelope(JSON.parse(j.ciphertext)).vault_id===envelope.vault_id:j.order.kind==='contribution')))??jobs.find(j=>envelope&&j.ciphertext&&parseEnvelope(JSON.parse(j.ciphertext)).vault_id===envelope.vault_id);if(live){setPending(jobs);if(found&&restored){const cfg=await configForJob(restored.chain,found,restored.trusted);await validateJob(found,cfg);if(found.attempt?.phase==='wallet_pending'){found.attempt.phase='signature_unknown';await saveJob(found);}setJob(found);if(found.ciphertext)setSelectedEnvelope(parseEnvelope(JSON.parse(found.ciphertext)));if(found.signingStarted)setStatus('Результат прежней подписи требует проверки. Повторная оплата заблокирована.');}else if(envelope||resume){const draft=await readCache<string>('saving-ciphertext');if(draft){const previous=parseEnvelope(JSON.parse(draft));if(!envelope||previous.vault_id===envelope.vault_id){setSelectedEnvelope(previous);if(envelope&&draft!==serializeEnvelope(envelope))setStatus('Продолжаем ранее подготовленный архив. Его байты сохранены; новые правки редактора не включаются в эту попытку.');}}}setInitialized(true);}})().catch(e=>{if(live){setError(nativeMessage(e.message));setInitialized(true);}});return()=>{live=false;};},[]);
 useEffect(()=>{if(initialized&&archive)void writeCache('saving-ciphertext',serializeEnvelope(archive)).catch(()=>setError('Не удалось сохранить архив на устройстве. Скачайте резервную копию; оплата не начата.'));},[archive,initialized]);
 const lock=useRef(false);
 async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);onBusy?.(true);setError('');try{await action();}catch(e){setError(job?.signingStarted&&!job.paymentSignature&&!job.reconciledSignature?'Ответ кошелька не установлен. Прежняя попытка сохранена; новая оплата заблокирована. Выполните проверку через «Продолжить сохранение».':nativeMessage(e&&typeof e==='object'&&'code'in e&&e.code===4001?'signature_cancelled':e instanceof Error?e.message:'requires_reconciliation'));if(e instanceof Error&&e.message==='cache_commit_failed'&&job?.signedPayment&&job.paymentSignature)downloadJson({schema:'sejire/native-job-package/v1',chain,job},`sejire-pending-${job.order.id}.json`);}finally{lock.current=false;setBusy(false);onBusy?.(false);}}
 async function authorize(){const latest=nativeSession();const candidate=latest?.trusted===anchor&&(!chain||latest.chain.versions.length>chain.versions.length)?latest.chain:chain;if(!candidate)throw Error('signed_configuration_required');const session=await trustChain(candidate,anchor);setChain(session.chain);return session;}
 async function create(){if(pilotEnabled()&&archive){if(parseAmount(contribution,9)!=='0')throw Error('Для этого пилота добровольный взнос должен быть 0 SOL');const old=(await cachedJobs()).find(j=>j.order.archive?.digest==='19133b897f69e1f0d43a55217a00adee6b6dfefb73f0f6228008f5c8a702e6c8');if(old)throw Error('Прежний заказ этого архива уже сохранён. Выберите его для продолжения, не создавайте новую оплату.');}const s=await authorize();if(archive)await readyForOrder(s.config,new TextEncoder().encode(serializeEnvelope(archive)).length,await envelopeDigest(serializeEnvelope(archive)));setPhase('Подтверждение в кошельке');const wallet=solWallet();await wallet.connect();if(!wallet.publicKey)throw Error('wallet_not_connected');const units=parseAmount(contribution,9);if(requiresLargeAmountConfirmation(units,'100000000000')&&!window.confirm(`Добровольный вклад ${formatAmount(units,9)} SOL. Проверьте сумму и адрес фонда ${s.config.wallets.fund}.`))return;
 const next=await newJob(s.config,wallet.publicKey.toString(),contribution,archive,wallet);await saveJob(next);await writeCache('active-saving',next.order.id);setJob(next);setPrepared(await preparePayment(s.config,next));setPhase('Подтверждение в кошельке');setStatus('Заказ подписан. Следующее подтверждение Phantom — платёж. Оператор видит заказ на этом устройстве.');}
 async function pay(){if(!consent)throw Error('exact_consent_required');await primary();}
 async function reconcile(value:NativeJob|undefined=job){if(!value)throw Error('select_order');setPhase('Проверка оплаты');const session=await authorize(),cfg=await configForJob(session.chain,value,session.trusted);
 if(!value.paymentSignature&&!value.reconciledSignature){const found=await findPaymentByReference(cfg,value.order);if(found.signature){value.reconciledSignature=found.signature;await saveJob(value);}else{setJob({...value});setStatus('Подтверждённый платёж по reference не найден. Это не гарантия отсутствия транзакции. Прежняя неопределённая попытка сохранена; новый платёж не создаётся.');return;}}
 let result:Awaited<ReturnType<typeof reconcileJob>>|undefined;for(let retry=0;retry<3;retry++){try{result=await reconcileJob(value,cfg,await cachedJobs());break;}catch(e){const error=e as Error&{details?:{retryAfterMs?:number}};if(error.message==='transaction_failed'&&value.attempt){value.attempt.phase='failed';await saveJob(value);}const delay=error.details?.retryAfterMs??(500*(retry+1));if(retry===2||delay>2000||!['requires_reconciliation','rpc-timeout','rpc-unavailable','rpc-rate-limited'].includes(error.message))throw e;await new Promise(resolve=>setTimeout(resolve,delay));}}if(!result)throw Error('requires_reconciliation');setPaid(true);if(value.attempt)value.attempt.phase='finalized';await saveJob(value);setJob({...value});setPhase('Ожидает исполнителя');setStatus(`Solana finalized: ${result.payment.signature}. Оплата подтверждена. Ожидает сохранения. Оператор видит задание на этом устройстве; межкомпьютерной очереди пока нет.`);
 if(value.arPlan){setPhase(value.arPlan.uploaded?'Проверка сохранения':'Отправка архива');const state=await nativeStatus(cfg.arweaveNodes,value.arPlan.id);if(state.status===200&&state.confirmed){const retrieved=await retrieveNative(cfg.arweaveNodes,value.arPlan.id,value.order.archive!.digest,value.order.archive!.bytes);await writeCache('retrieved-saving',{id:value.arPlan.id,serialized:retrieved.text});setStored(true);setStatus('Сохранено в Arweave: включение подтверждено, полученные байты и SHA-256 совпадают. Расшифровка выполняется отдельно вашим ключом.');}}
 }
 async function primary(){if(stored){location.hash='#/restore?saved=1';return;}if(!job){await create();return;}if(job.paymentSignature||job.reconciledSignature||job.signingStarted){try{await reconcile();}catch(e){if(e instanceof Error&&e.message==='requires_reconciliation'&&job.signedPayment&&job.attempt){const current=await authorize(),cfg=await configForJob(current.chain,job,current.trusted);await resumeSignedPayment(cfg,job);await reconcile();}else throw e;}return;}const session=await authorize(),cfg=await configForJob(session.chain,job,session.trusted);if(job.order.expiresAt<=Date.now()||Boolean(job.order.archive&&cfg.upload.acceptingUntil<=Date.now())){if(job.signingStarted||job.paymentSignature||job.reconciledSignature)throw Error('previous_payment_requires_reconciliation');if(!window.confirm('Срок прежнего заказа или готовности исполнителя истёк до подписи платежа. Создать связанный новый заказ с текущими условиями? Прежний заказ останется в истории.'))return;const wallet=solWallet();await wallet.connect();const next=await newJob(session.config,wallet.publicKey!.toString(),formatAmount(job.order.fundContribution.amount,9),archive,wallet,job.order.id);await saveJob(next);await writeCache('active-saving',next.order.id);setJob(next);setPrepared(await preparePayment(session.config,next));setStatus('Новый заказ связан с прежним. Проверьте сумму перед подписью платежа.');return;}if(!prepared){setPrepared(await preparePayment(cfg,job));setStatus('Подготовка обновлена. Проверьте актуальную комиссию и подтвердите платёж.');return;}const fresh=await preparePayment(cfg,job);setPrepared(fresh);if(prepared.feeLamports!==fresh.feeLamports){setStatus('Комиссия изменилась. Проверьте сумму и подтвердите ещё раз.');return;}const wallet=solWallet();await wallet.connect();try{await signAndBroadcast(cfg,job,wallet,fresh,import.meta.env.VITE_NATIVE_SOL_MAINNET==='1');}catch(e){setJob({...job});if(job.paymentSignature){await reconcile(job);return;}throw e;}setPrepared(undefined);setJob({...job});await reconcile(job);}
 const checked=useRef('');useEffect(()=>{if(initialized&&job&&(job.paymentSignature||job.reconciledSignature)&&checked.current!==job.order.id){checked.current=job.order.id;void run(()=>reconcile(job));}},[initialized,job?.order.id]);
 async function operator(){if(job)await writeCache('active-saving',job.order.id);location.hash=job?`#/admin?order=${job.order.id}`:'#/admin?prepare=1';}
 return <section className="checkout-panel" aria-label="Прямое сохранение Arweave"><h3>{archive?'Сохранить через Solana → Arweave':'Поддержать Фонд памяти поколений SEJIRE'}</h3>
 <section className="admin-panel"><h4>{treeName??(archive?'Зашифрованная семейная история':'Отдельная поддержка')}</h4><p>Ключ восстановления: {archive?'архив зашифрован; слова не передаются оператору. Храните резервную копию слов отдельно.':'для взноса не требуется'}</p><p>Сеть: {c?.environment==='devnet'?'тестовая Solana DEVNET':c?'основная (оплата выключена)':'настройки ещё не восстановлены'}</p><p>Сохранение: {formatAmount(job?.order.servicePayment.amount??(archive?c?.serviceLamports??'30000000':'0'),9)} SOL · комиссия сети отдельно: {prepared?formatAmount(prepared.feeLamports,9)+' SOL':'уточняется после подключения'}</p><p>Хранение оплачивает AR-резерв оператора. Автоматического SOL→AR нет.</p><ol className="admin-progress">{['Подготовка','Подтверждение в кошельке','Проверка оплаты','Ожидает исполнителя','Отправка архива','Проверка сохранения'].map((name,i)=><li key={name}>{i<['Подготовка','Подтверждение в кошельке','Проверка оплаты','Ожидает исполнителя','Отправка архива','Проверка сохранения'].indexOf(phase)?'✓':name===phase?'→':'○'} {name}</li>)}</ol>
 {!job&&<label>Добровольный вклад (SOL)<input aria-label="Добровольный вклад SOL" value={contribution} inputMode="decimal" onChange={e=>setContribution(e.target.value)}/></label>}
 {job&&<p>Добровольный вклад: {formatAmount(job.order.fundContribution.amount,9)} SOL. Итого: {formatAmount(job.order.total,9)} SOL + комиссия. Основная казна: {job.order.servicePayment.recipient.slice(0,6)}…{job.order.servicePayment.recipient.slice(-5)}; фонд: {job.order.fundContribution.recipient.slice(0,6)}…{job.order.fundContribution.recipient.slice(-5)}.</p>}
 <p>Phantom запросит подпись заказа и отдельную подпись платежа. Это два разных подтверждения.</p>
 <button className="btn" disabled={busy||!initialized||!c} onClick={()=>void run(primary)}>{stored?'Открыть сохранённое дерево':!job?'Подключить Phantom':paid||job.signingStarted||job.paymentSignature||!prepared?'Продолжить сохранение':'Подтвердить оплату'}</button>
 {(!c||error.includes('исполнител')||error.includes('бюджет'))&&<button className="btn ghost" onClick={()=>void run(operator)}>Подготовить это сохранение</button>}
 {paid&&!stored&&<button className="btn ghost" onClick={()=>void run(operator)}>Перейти к исполнению этого заказа</button>}
 {job?.signingStarted&&!job.paymentSignature&&!job.reconciledSignature&&<p role="note">{job.attempt?'Результат ответа кошелька требует сверки.':'Старая попытка: данные message и срока blockhash отсутствуют. Безопасное завершение не установлено.'}</p>}
 </section>
 <details className="saving-details"><summary>Подробнее · резервирование и диагностика</summary>
 {stored&&job&&<button className="btn ghost" onClick={()=>downloadJson(nativeReceipt(job),`sejire-native-receipt-${job.order.id}.json`)}>Скачать квитанцию</button>}
 <p>Ручной пилот без Turbo и обязательного облака. SOL оплачивает SEJIRE; отдельный AR-резерв владельца оплачивает Arweave. Автоматического SOL→AR нет.</p>
 <p>{c?.environment==='devnet'?'Solana Devnet: только тестовые SOL. Arweave-загрузка относится к другой сети и требует отдельного разрешения.':'Сеть определяется проверенной конфигурацией; mainnet-оплата выключена по умолчанию.'}</p>
 {archive&&<button className="btn ghost" onClick={()=>downloadEnvelope(archive)}>Скачать зашифрованную резервную копию</button>}
 {pilotEnabled()&&<label>Продолжить с ранее зашифрованным архивом<input type="file" accept=".json" aria-label="Согласованный зашифрованный архив" disabled={busy||Boolean(job)} onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{setSelectedEnvelope(await importPilotArchive(f));setStatus('Исходный архив проверен: 28365 байт для отправки, SHA-256 совпадает. Шифрование не повторялось.');});}}/></label>}
 <label>Доверенный genesis SHA-256<input aria-label="Доверенный genesis SHA-256" value={anchor} onChange={e=>setAnchor(e.target.value.trim())}/></label>
 <label>Подписанная конфигурация<input type="file" accept=".json" aria-label="Подписанная конфигурация" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{if(f.size>10*1024*1024)throw Error('file_too_large');setChain(JSON.parse(await f.text()));});}}/></label>
 <button className="btn ghost" disabled={busy} onClick={()=>void run(async()=>{await authorize();setStatus('Конфигурация проверена; адреса и цена зафиксируются в заказе.');})}>Проверить конфигурацию</button>
 {c&&<p>Цена сохранения: {formatAmount(c.serviceLamports,9)} SOL · сеть {c.environment}</p>}
 {pending.length>0&&<label>Продолжить прежний заказ<select aria-label="Продолжить прежний заказ" value={job?.order.id??''} onChange={e=>void run(async()=>{const found=pending.find(j=>j.order.id===e.target.value);if(!found)return;const s=await authorize(),cfg=await configForJob(s.chain,found,s.trusted);await validateJob(found,cfg);if(found.attempt?.phase==='wallet_pending'){found.attempt.phase='signature_unknown';await saveJob(found);}setJob(found);setPaid(false);setStored(false);setPrepared(undefined);if(found.ciphertext)setSelectedEnvelope(parseEnvelope(JSON.parse(found.ciphertext)));setStatus('Прежняя подпись сохранена. Сначала сверка, нового платежа нет.');})}><option value="">Выберите заказ</option>{pending.map(j=><option key={j.order.id} value={j.order.id}>{j.order.id}</option>)}</select></label>}
 {!job&&<><p>Ввод — дополнительный вклад, не общая сумма. По умолчанию 0. Отдельная поддержка не требует архива и платы за сохранение.</p><button className="btn" disabled={busy} onClick={()=>void run(create)}>Подключить Phantom и подписать заказ</button></>}
 {job&&<><dl><dt>Сеть / плательщик</dt><dd>{job.order.network} / {job.order.payer}</dd><dt>Сохранение → основная казна</dt><dd>{formatAmount(job.order.servicePayment.amount,9)} SOL → {job.order.servicePayment.recipient}</dd><dt>Вклад → Фонд памяти поколений</dt><dd>{formatAmount(job.order.fundContribution.amount,9)} SOL → {job.order.fundContribution.recipient}</dd><dt>Итого без комиссии</dt><dd>{formatAmount(job.order.total,9)} SOL</dd><dt>Комиссия сети отдельно</dt><dd>{prepared?formatAmount(prepared.feeLamports,9)+' SOL':'Уточняется перед подписью'}</dd></dl>
 {prepared&&<><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Подтверждаю показанные суммы, сеть и адреса</label><button className="btn" disabled={busy||!consent||(job.order.network==='mainnet-beta'&&import.meta.env.VITE_NATIVE_SOL_MAINNET!=='1')} onClick={()=>void run(pay)}>Оплатить {formatAmount(job.order.total,9)} SOL + комиссия</button></>}
 <button className="btn ghost" disabled={busy||Boolean(job.paymentSignature)||job.signingStarted} onClick={()=>void run(async()=>{const s=await authorize(),cfg=await configForJob(s.chain,job,s.trusted);setPrepared(await preparePayment(cfg,job));})}>Подготовить неподписанный платёж</button>
 <button className="btn" disabled={busy||!job.paymentSignature} onClick={()=>void run(reconcile)}>Сверить прежний платёж</button>
 <button className="btn ghost" onClick={()=>downloadJson({schema:'sejire/native-job-package/v1',chain,job},`sejire-job-${job.order.id}.json`)}>Экспорт задания для админки</button><p>Подпись транзакции: {job.paymentSignature??'ещё нет'}. Экспортируйте файл также при потере ответа. Receipt выдаётся после загрузки; оплата не означает сохранение.</p>
 </>}
 </details>
 {error&&<p role="alert">{error}</p>}{status&&<p role="status">{status}</p>}<button className="btn ghost" disabled={busy} onClick={onBack}>Назад</button></section>;
}
