import assert from 'node:assert/strict';
import {resolveHead} from './head';
import {LegacyLocatorProvider} from './providers/legacyLocatorProvider';
import {GraphqlVaultProvider} from './providers/graphqlVaultProvider';
import {validateMetadata,type TxMetadata} from './retrieve';
import {RecoveryFailure} from './errors';
import type {VerifiedVersion,RecoveryContext} from './types';
const vaultId='a'.repeat(32),id='A'.repeat(43);
const ctx={vaultId,signal:new AbortController().signal,fetcher:fetch} as RecoveryContext;
const locator=new LegacyLocatorProvider([{vaultId,txIds:[id],reason:'test'}]);
const loc=await locator.discover(ctx);
assert.equal(loc.status,'responded');assert.equal(loc.candidates[0].txId,id);assert.equal(loc.candidates[0].legacy,true);
assert.equal((await locator.discover({...ctx,vaultId:'b'.repeat(32)})).candidates.length,0);
const provider=new GraphqlVaultProvider('https://index.example/graphql');
const query=await provider.discover({...ctx,fetcher:async (_url,init)=>{
  const body=JSON.parse(String(init?.body));assert.equal(body.variables.vaultId,vaultId);
  return new Response(JSON.stringify({data:{transactions:{pageInfo:{hasNextPage:false},edges:[{node:{id,block:{height:42,timestamp:123}}}]}}}),{status:200});
}});
assert.equal(query.status,'responded');assert.equal(query.candidates.length,1);
assert.equal((await provider.discover({...ctx,fetcher:async()=>{throw Error('timeout');}})).status,'unavailable');
const meta:TxMetadata={id,tags:[{name:'App-Name',value:'SEJIRE'},{name:'Type',value:'vault-envelope'},{name:'Vault-Id',value:vaultId},{name:'Archive-SHA256',value:'a'.repeat(64)},{name:'Archive-Bytes',value:'100'},{name:'Schema',value:'sejire/envelope/v1'},{name:'Protocol-Version',value:'sejire/v0.3'}],blockHeight:42,blockTimestamp:123};
assert.doesNotThrow(()=>validateMetadata(meta,{txId:id,source:'test'},vaultId));
assert.throws(()=>validateMetadata({...meta,id:'B'.repeat(43)},{txId:id,source:'test'},vaultId));
assert.throws(()=>validateMetadata(meta,{txId:id,source:'test'},'b'.repeat(32)),(error:unknown)=>error instanceof RecoveryFailure&&error.code==='VAULT_ID_MISMATCH');
assert.throws(()=>validateMetadata({...meta,tags:meta.tags.filter(t=>t.name!=='Vault-Id')},{txId:id,source:'test'},vaultId));
assert.doesNotThrow(()=>validateMetadata({...meta,tags:meta.tags.filter(t=>t.name!=='Vault-Id')},{txId:id,source:'legacy',legacy:true},vaultId));
const version=(txId:string,parentTxId:string|null,blockHeight:number):VerifiedVersion=>({txId,parentTxId,blockHeight,blockTimestamp:blockHeight,vault:{schema:'sejire/vault/v1',vault_id:vaultId,updated_at:'',trees:{},active_tree_id:null},sources:['test']});
const v1=version('A'.repeat(43),null,1),v2=version('B'.repeat(43),v1.txId,2),v3=version('C'.repeat(43),v2.txId,3);
assert.equal(resolveHead([v2,v1,v3]).head.txId,v3.txId);
assert.equal(resolveHead([v1,v2,version('D'.repeat(43),v1.txId,4)]).forks.length,1);
console.log('Recovery provider, metadata and HEAD selftests passed');
